// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace MidManStudio.DixScript.Native
{
    internal static unsafe partial class MdixNative
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "mdix_ffi";
#endif
        





        /// <summary>
        ///  Returns a static pointer to the DixScript FFI version string.
        ///  Do NOT pass this pointer to mdix_free_string() — it is a static allocation.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_version();

        /// <summary>
        ///  Load and compile a .mdix source file from disk.
        ///  Returns an opaque handle on success, null on failure (check mdix_get_last_error).
        ///  Caller must free with mdix_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_load(byte* path);

        /// <summary>
        ///  Compile and load .mdix source from an in-memory string.
        ///  Useful for Unity TextAssets and embedded configs.
        ///  Returns an opaque handle on success, null on failure.
        ///  Caller must free with mdix_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_load_str", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_load_str(byte* source);

        /// <summary>
        ///  Free a handle created by any mdix_load* function.
        ///  Passing null is safe. Do not call twice on the same pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mdix_free(void* handle);

        /// <summary>
        ///  Load an encrypted .mdix.enc file using a .mdix.key file for key resolution.
        ///  Pass null for key_path to auto-detect the key file next to the enc file.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_load_encrypted", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_load_encrypted(byte* enc_path, byte* key_path);

        /// <summary>
        ///  Load an encrypted .mdix.enc file using a password for key derivation.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_load_encrypted_password", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_load_encrypted_password(byte* enc_path, byte* password);

        /// <summary>
        ///  Load encrypted data from raw bytes with key file content provided as a string.
        ///  Intended for platforms without filesystem access (asset bundles, network delivery).
        ///  Pass null for password if the key file does not use password mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_load_encrypted_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_load_encrypted_bytes(byte* encrypted_bytes, int byte_count, byte* key_file_content, byte* password);

        /// <summary>
        ///  Returns true if the handle is non-null (i.e. load succeeded).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_is_valid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_is_valid(void* handle);

        /// <summary>
        ///  Returns the number of entries in the flat data map, or -1 if handle is null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_entry_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mdix_entry_count(void* handle);

        /// <summary>
        ///  Returns true if the source file was encrypted.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_is_encrypted", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_is_encrypted(void* handle);

        /// <summary>
        ///  Returns true if the source file was compressed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_is_compressed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_is_compressed(void* handle);

        /// <summary>
        ///  Returns the runtime version string from the loaded DixData.
        ///  Caller must free the returned string with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_loaded_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_loaded_version(void* handle);

        /// <summary>
        ///  Returns all keys in the flat data map as a null-terminated C string array.
        ///  Writes the count to out_count. Caller must free with mdix_free_string_array.
        ///  Includes synthetic indexed keys (tags[0], server.host, etc.).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_all_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte** mdix_get_all_keys(void* handle, int* out_count);

        /// <summary>
        ///  Read a value from the @CONFIG section by key (e.g. "version", "author").
        ///  Returns null if the section is absent or the key does not exist.
        ///  Caller must free the returned string with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_config_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_config_value(void* handle, byte* key);

        /// <summary>
        ///  Validate .mdix source text without loading the result.
        ///
        ///  Runs the full compilation pipeline (tokenize → parse → semantic analysis →
        ///  AST enhance → value resolve). Returns true on success; on failure, the
        ///  error detail is available via mdix_get_last_error().
        ///
        ///  Useful for Unity editor tooling — validate before shipping.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_validate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_validate(byte* source);

        /// <summary>
        ///  Returns the MdixType discriminant for the value at path, or MdixType::Unknown
        ///  if the path does not exist or the handle is null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern MdixType mdix_get_type(void* handle, byte* path);

        /// <summary>
        ///  Returns the element count of an Array or Tuple at path, or -1 if the path
        ///  does not exist, is not a collection, or the handle is null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_array_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mdix_get_array_length(void* handle, byte* path);

        /// <summary>
        ///  Get a string value at path.
        ///  Also returns Date, Timestamp, HexColor, Blob, and Regex values as strings.
        ///  Caller must free the returned string with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_string(void* handle, byte* path);

        /// <summary>
        ///  Get a 32-bit integer at path. Also works on Enum paths (returns the integer value).
        ///  Returns 0 on failure; check mdix_get_last_error() to distinguish from a real 0.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mdix_get_int(void* handle, byte* path);

        /// <summary>
        ///  Get a 64-bit integer at path. Also accepts Int values (widened without loss).
        ///  Returns 0 on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_long", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern long mdix_get_long(void* handle, byte* path);

        /// <summary>
        ///  Get a 32-bit float at path. Returns 0.0 on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float mdix_get_float(void* handle, byte* path);

        /// <summary>
        ///  Get a 64-bit double at path. Returns 0.0 on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double mdix_get_double(void* handle, byte* path);

        /// <summary>
        ///  Get a boolean at path. Returns false on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_bool", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_get_bool(void* handle, byte* path);

        /// <summary>
        ///  Returns the enum type name at path (e.g. "WeaponClass").
        ///  Returns null if the path does not exist or is not an enum.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_enum_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_enum_name(void* handle, byte* path);

        /// <summary>
        ///  Returns the enum field name at path (e.g. "ASSAULT_RIFLE").
        ///  Returns null if the path does not exist or is not an enum.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_enum_field", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_enum_field(void* handle, byte* path);

        /// <summary>
        ///  Serialize the raw DixValue at path to a JSON string.
        ///
        ///  Useful for reading Object or Array values wholesale into C# for further
        ///  processing. Note: DixValue::Enum serializes as {"enum_name":...,"value":N}
        ///  via serde — use mdix_get_int on enum paths to get just the integer.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_json(void* handle, byte* path);

        /// <summary>
        ///  Select all values matching a dotted path pattern and return them as a JSON array.
        ///
        ///  Use `*` as a wildcard for a single path segment:
        ///    "server.*"   → all direct children of the server table property
        ///    "weapons.*"  → all direct children of the weapons object
        ///
        ///  LIMITATION: bracket-indexed paths (enemies[0].name) do not match dot
        ///  wildcards. Use mdix_get_array_length + mdix_get_* with explicit indexed
        ///  paths for array item access from the C# side.
        ///
        ///  Caller must free the returned string with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_select_many_as_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_select_many_as_json(void* handle, byte* pattern);

        /// <summary>
        ///  Returns true if a value exists at path.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_exists", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_exists(void* handle, byte* path);

        /// <summary>
        ///  Returns the direct child key names under prefix as a C string array.
        ///  Pass an empty string for top-level keys.
        ///  Writes the count to out_count. Caller must free with mdix_free_string_array().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte** mdix_get_keys(void* handle, byte* prefix, int* out_count);

        /// <summary>
        ///  Free a C string returned by any mdix getter function.
        ///  Do NOT call on the static pointer from mdix_version(). Passing null is safe.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mdix_free_string(byte* s);

        /// <summary>
        ///  Free a string array returned by mdix_get_keys() or mdix_get_all_keys().
        ///  count must match the value written to out_count by the original call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_free_string_array", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mdix_free_string_array(byte** arr, int count);

        /// <summary>
        ///  Returns a pointer to the last error string set on this thread, or null if
        ///  no error is pending. Valid only until the next mdix_* call on this thread.
        ///  Do NOT free this pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_get_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_get_last_error();

        /// <summary>
        ///  Clear the pending error on this thread.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_clear_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mdix_clear_error();

        /// <summary>
        ///  Export the loaded data as a JSON string.
        ///  Enum values are emitted as plain integers (not as JSON objects).
        ///  Pass indented=true for pretty-printed output.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_to_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_to_json(void* handle, [MarshalAs(UnmanagedType.U1)] bool indented);

        /// <summary>
        ///  Export the loaded data as .mdix source text.
        ///  Caller must free with mdix_free_string().
        ///
        ///  FIX: previously returned *mut c_void — corrected to *mut c_char.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_to_mdix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_to_mdix(void* handle, MdixFormatMode mode);

        /// <summary>
        ///  Export the loaded data as TOML.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_to_toml", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_to_toml(void* handle);

        /// <summary>
        ///  Format .mdix source text according to the given mode.
        ///  Minified mode removes all unnecessary whitespace.
        ///  Compact mode collapses blank lines and strips trailing whitespace.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_format_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_format_source(byte* source, MdixFormatMode mode);

        /// <summary>
        ///  Minify .mdix source — remove all unnecessary whitespace using the tokenizer.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_minify_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_minify_source(byte* source);

        /// <summary>
        ///  Compact .mdix source — strip trailing whitespace and collapse blank lines.
        ///  Preserves indentation and code structure. Lighter than minify.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_compact_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_compact_source(byte* source);

        /// <summary>
        ///  Strip all comments from .mdix source. Content inside string literals is preserved.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_strip_comments", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_strip_comments(byte* source);

        /// <summary>
        ///  Create an empty builder for constructing new save data.
        ///  Caller must free with mdix_builder_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_builder_new();

        /// <summary>
        ///  Create a builder pre-populated from an existing loaded handle.
        ///
        ///  Copies all root-level structural values from the handle into the builder.
        ///  Synthetic indexed children (tags[0], server.host, etc.) are stripped so
        ///  only values that map to valid .mdix identifiers remain editable.
        ///
        ///  Typical use: load a save file → fork into builder → change a few fields
        ///  → mdix_builder_save back to disk. The original handle remains valid.
        ///
        ///  Caller must free the returned builder with mdix_builder_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_from_handle", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_builder_from_handle(void* handle);

        /// <summary>
        ///  Free a builder created by mdix_builder_new or mdix_builder_from_handle.
        ///  Passing null is safe. Do not call twice on the same pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mdix_builder_free(void* builder);

        /// <summary>
        ///  Returns the number of entries currently in the builder, or -1 if null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_entry_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mdix_builder_entry_count(void* builder);

        /// <summary>
        ///  Clear all entries from the builder. Returns true on success.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_clear", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_clear(void* builder);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_string(void* builder, byte* path, byte* value);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_int(void* builder, byte* path, int value);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_long", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_long(void* builder, byte* path, long value);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_float(void* builder, byte* path, float value);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_double(void* builder, byte* path, double value);

        [DllImport(__DllName, EntryPoint = "mdix_builder_set_bool", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_set_bool(void* builder, byte* path, [MarshalAs(UnmanagedType.U1)] bool value);

        /// <summary>
        ///  Remove the entry at path from the builder. Returns true if it existed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_remove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_remove(void* builder, byte* path);

        /// <summary>
        ///  Returns true if the builder contains an entry at path.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_has_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_has_key(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_builder_get_string(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mdix_builder_get_int(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_long", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern long mdix_builder_get_long(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_float", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float mdix_builder_get_float(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double mdix_builder_get_double(void* builder, byte* path);

        [DllImport(__DllName, EntryPoint = "mdix_builder_get_bool", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_get_bool(void* builder, byte* path);

        /// <summary>
        ///  Serialize the builder's entries and write them to a .mdix file at path.
        ///  Parent directories are created if they do not exist.
        ///  Returns true on success.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool mdix_builder_save(void* builder, byte* path);

        /// <summary>
        ///  Serialize the builder's entries to a pretty-printed .mdix string.
        ///  Caller must free with mdix_free_string().
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_builder_to_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* mdix_builder_to_string(void* builder);

        /// <summary>
        ///  Parse a JSON string and load it as a DixData handle.
        ///  Caller must free with mdix_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_from_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_from_json(byte* source);

        /// <summary>
        ///  Parse a TOML string and load it as a DixData handle.
        ///  Caller must free with mdix_free when done.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mdix_from_toml", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* mdix_from_toml(byte* source);


    }


    /// <summary>
    ///  Type discriminants returned by mdix_get_type().
    ///  Values are stable — the C# MdixValueType enum MUST match exactly.
    ///  Numeric types are contiguous: Int=2, Long=3, Float=4, Double=5.
    /// </summary>
    internal enum MdixType : int
    {
        Unknown = -1,
        Null = 0,
        Bool = 1,
        Int = 2,
        Long = 3,
        Float = 4,
        Double = 5,
        String = 6,
        Date = 7,
        Timestamp = 8,
        HexColor = 9,
        Blob = 10,
        Regex = 11,
        Array = 12,
        Object = 13,
        Tuple = 14,
        Enum = 15,
    }

    /// <summary>
    ///  Output format mode for mdix_to_mdix() and mdix_format_source().
    /// </summary>
    internal enum MdixFormatMode : int
    {
        Default = 0,
        Pretty = 1,
        Compact = 2,
        Minified = 3,
    }


}
