// AUTO-EXTRACTED from real CLDR v48 data (unicode-org/cldr-json,
// cldr-core/supplemental/plurals.json), collapsed to integer-only
// behavior and verified against an independent re-evaluation across
// 67,710 (locale, count) pairs with zero mismatches. See
// architecture-and-design notes for the extraction method. DO NOT
// hand-edit -- regenerate from the source data if CLDR updates.
using System;
using System.Collections.Generic;

namespace MidManStudio.Mdix.Localization
{
    public static class CldrPluralFamilies
    {
        public static readonly IReadOnlyDictionary<string, PluralRuleFamily> All = new Dictionary<string, PluralRuleFamily>
        {
            // Family 1 -- 106 locales: af, an, asa, ast, az, bal, bem, bez, bg, brx, ce, cgg, chr, ckb, da, de, dv, ee, el, en, eo, et, eu, fi, fo, fur, fy, gl, gsw, ha, haw, hu, ia, ie, io, jgo, jmc, ka, kaj, kcg, kk, kkj, kl, ks, ksb, ku, ky, lb, lg, lij, mas, mgo, ml, mn, mr, nah, nb, nd, ne, nl, nn, nnh, no, nr, ny, nyn, om, or, os, pap, ps, rm, rof, rwk, saq, sc, sd, sdh, seh, sn, so, sq, ss, ssy, st, sv, sw, syr, ta, te, teo, tig, tk, tn, tr, ts, ug, ur, uz, ve, vo, vun, wae, xh, xog, yi
            ["one_other"] = new PluralRuleFamily("one_other", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: null, many: null),
            // Family 2 -- 34 locales: bm, bo, dz, hnj, id, ig, ii, ja, jbo, jv, jw, kde, kea, km, ko, lkt, lo, ms, my, nqo, osa, sah, ses, sg, su, th, to, tpi, und, vi, wo, yo, yue, zh
            ["other_only"] = new PluralRuleFamily("other_only", zero: null, one: null, two: null, few: null, many: null),
            // Family 3 -- 25 locales: ak, am, as, bho, bn, csw, doi, fa, ff, gu, guw, hi, hy, kab, kn, kok, ln, mg, nso, pa, pcm, si, ti, wa, zu
            ["zero_one_are_one_other"] = new PluralRuleFamily("zero_one_are_one_other", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 1) }) }) }), two: null, few: null, many: null),
            // Family 4 -- 10 locales: he, iu, naq, sat, se, sma, smi, smj, smn, sms
            ["one_two_other"] = new PluralRuleFamily("one_two_other", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2) }) }) }), few: null, many: null),
            // Family 5 -- 7 locales: ca, es, it, lld, pt-PT, scn, vec
            ["one_other_millions_many"] = new PluralRuleFamily("one_other_millions_many", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: null, many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (0, 0) }), new PluralRelation(1000000, false, new (int, int)[] { (0, 0) }) }) })),
            // Family 6 -- 4 locales: blo, cv, ksh, lag
            ["zero_one_other"] = new PluralRuleFamily("zero_one_other", zero: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }) }), one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: null, many: null),
            // Family 7 -- 4 locales: bs, hr, sh, sr
            ["bs_hr_sr_type"] = new PluralRuleFamily("bs_hr_sr_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 11) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 4) }), new PluralRelation(100, true, new (int, int)[] { (12, 14) }) }) }), many: null),
            // Family 8 -- 3 locales: be, ru, uk
            ["ru_be_uk_type"] = new PluralRuleFamily("ru_be_uk_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 11) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 4) }), new PluralRelation(100, true, new (int, int)[] { (12, 14) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (0, 0) }) }), new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (5, 9) }) }), new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (11, 14) }) }) })),
            // Family 9 -- 3 locales: ceb, fil, tl
            ["fil_ceb_tl_type"] = new PluralRuleFamily("fil_ceb_tl_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1), (2, 2), (3, 3) }) }), new PluralAndGroup(new[] { new PluralRelation(10, true, new (int, int)[] { (4, 4), (6, 6), (9, 9) }) }) }), two: null, few: null, many: null),
            // Family 10 -- 3 locales: dsb, hsb, sl
            ["dsb_hsb_sl_type"] = new PluralRuleFamily("dsb_hsb_sl_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (3, 4) }) }) }), many: null),
            // Family 11 -- 2 locales: ar, ars
            ["ar_type"] = new PluralRuleFamily("ar_type", zero: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }) }), one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (3, 10) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (11, 99) }) }) })),
            // Family 12 -- 2 locales: cs, sk
            ["cs_sk_type"] = new PluralRuleFamily("cs_sk_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 4) }) }) }), many: null),
            // Family 13 -- 2 locales: fr, pt
            ["fr_pt_type"] = new PluralRuleFamily("fr_pt_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0), (1, 1) }) }) }), two: null, few: null, many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (0, 0) }), new PluralRelation(1000000, false, new (int, int)[] { (0, 0) }) }) })),
            // Family 14 -- 2 locales: is, mk
            ["is_mk_type"] = new PluralRuleFamily("is_mk_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 11) }) }) }), two: null, few: null, many: null),
            // Family 15 -- 2 locales: lv, prg
            ["lv_prg_type"] = new PluralRuleFamily("lv_prg_type", zero: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (0, 0) }) }), new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (11, 19) }) }) }), one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 11) }) }) }), two: null, few: null, many: null),
            // Family 16 -- 2 locales: mo, ro
            ["ro_mo_type"] = new PluralRuleFamily("ro_mo_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }), new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (1, 1) }), new PluralRelation(100, false, new (int, int)[] { (1, 19) }) }) }), many: null),
            // Family 17 -- 1 locales: br
            ["br_type"] = new PluralRuleFamily("br_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 11), (71, 71), (91, 91) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 2) }), new PluralRelation(100, true, new (int, int)[] { (12, 12), (72, 72), (92, 92) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (3, 4), (9, 9) }), new PluralRelation(100, true, new (int, int)[] { (10, 19), (70, 79), (90, 99) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (0, 0) }), new PluralRelation(1000000, false, new (int, int)[] { (0, 0) }) }) })),
            // Family 18 -- 1 locales: cy
            ["cy_type"] = new PluralRuleFamily("cy_type", zero: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }) }), one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (3, 3) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (6, 6) }) }) })),
            // Family 19 -- 1 locales: ga
            ["ga_type"] = new PluralRuleFamily("ga_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (3, 6) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (7, 10) }) }) })),
            // Family 20 -- 1 locales: gd
            ["gd_type"] = new PluralRuleFamily("gd_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1), (11, 11) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2), (12, 12) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (3, 10), (13, 19) }) }) }), many: null),
            // Family 21 -- 1 locales: gv
            ["gv_type"] = new PluralRuleFamily("gv_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (0, 0), (20, 20), (40, 40), (60, 60), (80, 80) }) }) }), many: null),
            // Family 22 -- 1 locales: kw
            ["kw_type"] = new PluralRuleFamily("kw_type", zero: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }) }), one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (2, 2), (22, 22), (42, 42), (62, 62), (82, 82) }) }), new PluralAndGroup(new[] { new PluralRelation(1000, false, new (int, int)[] { (0, 0) }), new PluralRelation(100000, false, new (int, int)[] { (1000, 20000), (40000, 40000), (60000, 60000), (80000, 80000) }) }), new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (0, 0) }), new PluralRelation(1000000, false, new (int, int)[] { (100000, 100000) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (3, 3), (23, 23), (43, 43), (63, 63), (83, 83) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (1, 1) }), new PluralRelation(100, false, new (int, int)[] { (1, 1), (21, 21), (41, 41), (61, 61), (81, 81) }) }) })),
            // Family 23 -- 1 locales: lt
            ["lt_type"] = new PluralRuleFamily("lt_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (1, 1) }), new PluralRelation(100, true, new (int, int)[] { (11, 19) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 9) }), new PluralRelation(100, true, new (int, int)[] { (11, 19) }) }) }), many: null),
            // Family 24 -- 1 locales: mt
            ["mt_type"] = new PluralRuleFamily("mt_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 2) }) }) }), few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }), new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (3, 10) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (11, 19) }) }) })),
            // Family 25 -- 1 locales: pl
            ["pl_type"] = new PluralRuleFamily("pl_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (2, 4) }), new PluralRelation(100, true, new (int, int)[] { (12, 14) }) }) }), many: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, true, new (int, int)[] { (1, 1) }), new PluralRelation(10, false, new (int, int)[] { (0, 1) }) }), new PluralAndGroup(new[] { new PluralRelation(10, false, new (int, int)[] { (5, 9) }) }), new PluralAndGroup(new[] { new PluralRelation(100, false, new (int, int)[] { (12, 14) }) }) })),
            // Family 26 -- 1 locales: shi
            ["shi_type"] = new PluralRuleFamily("shi_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 0) }) }), new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (1, 1) }) }) }), two: null, few: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (2, 10) }) }) }), many: null),
            // Family 27 -- 1 locales: tzm
            ["tzm_type"] = new PluralRuleFamily("tzm_type", zero: null, one: new PluralCondition(new[] { new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (0, 1) }) }), new PluralAndGroup(new[] { new PluralRelation(null, false, new (int, int)[] { (11, 99) }) }) }), two: null, few: null, many: null),
        };
    }
}
