
//! Static signature tables for hover documentation.
//! Extracted from hover.rs so the data is easy to edit independently.
//!
//! Each entry is a tuple: (type_or_class, method_name, params_string, return_type, example)
//! for INSTANCE_METHOD_SIGS, or (class, method, signature, description, example) for STATIC_SIGS.

// ── Instance method signatures ────────────────────────────────────────────────

/// Typed signatures for builtin instance methods.
/// (type_name, method_name, params_with_types, return_type, example)
pub static INSTANCE_METHOD_SIGS: &[(&str, &str, &str, &str, &str)] = &[
    // ── String ──────────────────────────────────────────────────────────────
    ("string", "length",      "",                                     "int",    "\"hello\".length() // → 5"),
    ("string", "toUpper",     "",                                     "string", "\"hello\".toUpper() // → \"HELLO\""),
    ("string", "toLower",     "",                                     "string", "\"HELLO\".toLower() // → \"hello\""),
    ("string", "trim",        "",                                     "string", "\"  hi  \".trim() // → \"hi\""),
    ("string", "isEmpty",     "",                                     "bool",   "\"\".isEmpty() // → true"),
    ("string", "isBlank",     "",                                     "bool",   "\"   \".isBlank() // → true"),
    ("string", "contains",    "substr: string",                       "bool",   "\"hello world\".contains(\"world\")"),
    ("string", "startsWith",  "prefix: string",                       "bool",   "\"hello\".startsWith(\"he\")"),
    ("string", "endsWith",    "suffix: string",                       "bool",   "\"hello\".endsWith(\"lo\")"),
    ("string", "indexOf",     "substr: string",                       "int",    "\"hello\".indexOf(\"l\") // → 2"),
    ("string", "lastIndexOf", "substr: string",                       "int",    "\"hello\".lastIndexOf(\"l\") // → 3"),
    ("string", "charAt",      "index: int",                           "string", "\"hello\".charAt(0) // → \"h\""),
    ("string", "replace",     "old: string, new: string",             "string", "\"hello\".replace(\"l\", \"r\")"),
    ("string", "split",       "separator: string",                    "array",  "\"a,b,c\".split(\",\") // → [\"a\",\"b\",\"c\"]"),
    ("string", "substring",   "start: int, length: int",              "string", "\"hello\".substring(1, 3) // → \"ell\""),
    ("string", "padLeft",     "width: int, char: string",             "string", "\"hi\".padLeft(5, \"0\") // → \"000hi\""),
    ("string", "padRight",    "width: int, char: string",             "string", "\"hi\".padRight(5, \" \")"),
    ("string", "repeat",      "count: int",                           "string", "\"ab\".repeat(3) // → \"ababab\""),
    ("string", "reverse",     "",                                     "string", "\"hello\".reverse() // → \"olleh\""),
    ("string", "toInt",       "",                                     "int",    "\"42\".toInt() // → 42"),
    ("string", "toDouble",    "",                                     "double", "\"3.14\".toDouble()"),
    ("string", "toBool",      "",                                     "bool",   "\"true\".toBool()"),
    // ── Array ────────────────────────────────────────────────────────────────
    ("array",  "length",      "",                                     "int",    "[1,2,3].length() // → 3"),
    ("array",  "isEmpty",     "",                                     "bool",   "[].isEmpty() // → true"),
    ("array",  "first",       "",                                     "any",    "[1,2,3].first() // → 1"),
    ("array",  "last",        "",                                     "any",    "[1,2,3].last() // → 3"),
    ("array",  "get",         "index: int",                           "any",    "[\"a\",\"b\"].get(0) // → \"a\""),
    ("array",  "set",         "index: int, value",                    "array",  "[1,2,3].set(0, 10)"),
    ("array",  "push",        "value",                                "array",  "[1,2].push(3) // → [1,2,3]"),
    ("array",  "pop",         "",                                     "array",  "[1,2,3].pop() // removes last"),
    ("array",  "unshift",     "value",                                "array",  "[2,3].unshift(1) // → [1,2,3]"),
    ("array",  "shift",       "",                                     "array",  "[1,2,3].shift() // removes first"),
    ("array",  "reverse",     "",                                     "array",  "[1,2,3].reverse()"),
    ("array",  "sort",        "",                                     "array",  "[3,1,2].sort()"),
    ("array",  "flatten",     "",                                     "array",  "[[1,2],[3]].flatten()"),
    ("array",  "distinct",    "",                                     "array",  "[1,1,2].distinct()"),
    ("array",  "sum",         "",                                     "double", "[1,2,3].sum() // → 6.0"),
    ("array",  "average",     "",                                     "double", "[1,2,3].average() // → 2.0"),
    ("array",  "min",         "",                                     "double", "[3,1,2].min() // → 1.0"),
    ("array",  "max",         "",                                     "double", "[3,1,2].max() // → 3.0"),
    ("array",  "contains",    "value",                                "bool",   "[1,2,3].contains(2) // → true"),
    ("array",  "indexOf",     "value",                                "int",    "[1,2,3].indexOf(2) // → 1"),
    ("array",  "lastIndexOf", "value",                                "int",    "[1,2,2].lastIndexOf(2) // → 2"),
    ("array",  "count",       "value",                                "int",    "[1,1,2].count(1) // → 2"),
    ("array",  "slice",       "start: int, end: int",                 "array",  "[1,2,3,4].slice(1, 3) // → [2,3]"),
    ("array",  "join",        "separator: string",                    "string", "[\"a\",\"b\"].join(\",\") // → \"a,b\""),
    ("array",  "concat",      "other: array",                         "array",  "[1,2].concat([3,4])"),
    ("array",  "filter",      "excludeValue",                         "array",  "[1,2,1].filter(1) // removes 1s"),
    ("array",  "random",      "",                                     "any",    "[1,2,3].random() // random element"),
    ("array",  "at",          "index: int",                           "any",    "[1,2,3].at(-1) // last element"),
    // ── Tuple ────────────────────────────────────────────────────────────────
    ("tuple",  "length",      "",                                     "int",    "t:(1,\"a\").length() // → 2"),
    ("tuple",  "first",       "",                                     "any",    "t:(1,\"a\").first() // → 1"),
    ("tuple",  "second",      "",                                     "any",    "t:(1,\"a\").second() // → \"a\""),
    ("tuple",  "third",       "",                                     "any",    "t:(1,2,3).third() // → 3"),
    ("tuple",  "fourth",      "",                                     "any",    "t:(1,2,3,4).fourth()"),
    ("tuple",  "fifth",       "",                                     "any",    "t:(1,2,3,4,5).fifth()"),
    ("tuple",  "sixth",       "",                                     "any",    "t:(1,2,3,4,5,6).sixth()"),
    ("tuple",  "get",         "index: int",                           "any",    "t:(1,2).get(1) // → 2"),
    ("tuple",  "at",          "index: int",                           "any",    "t:(1,2).at(0)"),
    ("tuple",  "toArray",     "",                                     "array",  "t:(1,2,3).toArray()"),
    ("tuple",  "reverse",     "",                                     "tuple",  "t:(1,2,3).reverse()"),
    ("tuple",  "contains",    "value",                                "bool",   "t:(1,2).contains(2) // → true"),
    ("tuple",  "containsAny", "arr: array",                           "bool",   "t:(1,2).containsAny([1,5])"),
    ("tuple",  "swap",        "i1: int, i2: int",                     "tuple",  "t:(1,2,3).swap(0, 2) // → t:(3,2,1)"),
    // ── Int ──────────────────────────────────────────────────────────────────
    ("int",    "abs",         "",                                     "int",    "(-42).abs() // → 42"),
    ("int",    "sign",        "",                                     "int",    "(-5).sign() // → -1"),
    ("int",    "isEven",      "",                                     "bool",   "4.isEven() // → true"),
    ("int",    "isOdd",       "",                                     "bool",   "3.isOdd() // → true"),
    ("int",    "isPositive",  "",                                     "bool",   "5.isPositive() // → true"),
    ("int",    "isNegative",  "",                                     "bool",   "(-3).isNegative() // → true"),
    ("int",    "toLong",      "",                                     "long",   "42.toLong()"),
    ("int",    "toFloat",     "",                                     "float",  "42.toFloat()"),
    ("int",    "toDouble",    "",                                     "double", "42.toDouble()"),
    ("int",    "toString",    "",                                     "string", "42.toString() // → \"42\""),
    ("int",    "clamp",       "min: int, max: int",                   "int",    "5.clamp(0, 10) // → 5"),
    // ── Long ─────────────────────────────────────────────────────────────────
    ("long",   "abs",         "",                                     "long",   "(-9000000000L).abs()"),
    ("long",   "sign",        "",                                     "int",    "(-1L).sign() // → -1"),
    ("long",   "isEven",      "",                                     "bool",   "4L.isEven()"),
    ("long",   "isOdd",       "",                                     "bool",   "3L.isOdd()"),
    ("long",   "fitsInInt",   "",                                     "bool",   "9000000000L.fitsInInt() // → false"),
    ("long",   "toInt",       "",                                     "int",    "100L.toInt() // truncating cast"),
    ("long",   "toDouble",    "",                                     "double", "9000000000L.toDouble()"),
    ("long",   "toString",    "",                                     "string", "9000000000L.toString()"),
    // ── Float ────────────────────────────────────────────────────────────────
    ("float",  "abs",         "",                                     "float",  "(-3.14f).abs()"),
    ("float",  "round",       "decimals: int = 0",                    "float",  "3.14159f.round(2) // → 3.14f"),
    ("float",  "floor",       "",                                     "int",    "3.7f.floor() // → 3"),
    ("float",  "ceil",        "",                                     "int",    "3.2f.ceil() // → 4"),
    ("float",  "sign",        "",                                     "int",    "(-1.0f).sign() // → -1"),
    ("float",  "isNaN",       "",                                     "bool",   "myFloat.isNaN()"),
    ("float",  "isInfinity",  "",                                     "bool",   "myFloat.isInfinity()"),
    ("float",  "isFinite",    "",                                     "bool",   "myFloat.isFinite()"),
    ("float",  "toDouble",    "",                                     "double", "3.14f.toDouble()"),
    ("float",  "toInt",       "",                                     "int",    "3.7f.toInt() // → 3 (truncated)"),
    ("float",  "toString",    "",                                     "string", "3.14f.toString()"),
    ("float",  "clamp",       "min: float, max: float",               "float",  "1.5f.clamp(0.0f, 1.0f)"),
    // ── Double ───────────────────────────────────────────────────────────────
    ("double", "abs",         "",                                     "double", "(-3.14).abs()"),
    ("double", "round",       "decimals: int = 0",                    "double", "3.14159.round(2) // → 3.14"),
    ("double", "floor",       "",                                     "int",    "3.7.floor() // → 3"),
    ("double", "ceil",        "",                                     "int",    "3.2.ceil() // → 4"),
    ("double", "sign",        "",                                     "int",    "(-1.0).sign() // → -1"),
    ("double", "isNaN",       "",                                     "bool",   "myDouble.isNaN()"),
    ("double", "isInfinity",  "",                                     "bool",   "myDouble.isInfinity()"),
    ("double", "isFinite",    "",                                     "bool",   "myDouble.isFinite()"),
    ("double", "toLong",      "",                                     "long",   "3.99.toLong() // → 3L"),
    ("double", "toInt",       "",                                     "int",    "3.99.toInt() // → 3"),
    ("double", "toFloat",     "",                                     "float",  "3.14.toFloat()"),
    ("double", "toString",    "",                                     "string", "3.14.toString()"),
    ("double", "clamp",       "min: double, max: double",             "double", "1.5.clamp(0.0, 1.0)"),
    // ── Object ───────────────────────────────────────────────────────────────
    ("object", "count",       "",                                     "int",    "obj.count() // number of keys"),
    ("object", "keys",        "",                                     "array",  "obj.keys() // → [\"name\",\"age\"]"),
    ("object", "values",      "",                                     "array",  "obj.values()"),
    ("object", "entries",     "",                                     "array",  "obj.entries() // → array of t:(key,val)"),
    ("object", "toArray",     "",                                     "array",  "obj.toArray()"),
    ("object", "get",         "key: string",                          "any",    "obj.get(\"name\") // → value or null"),
    ("object", "has",         "key: string",                          "bool",   "obj.has(\"name\") // → true/false"),
    ("object", "containsValue","value",                               "bool",   "obj.containsValue(42)"),
    ("object", "add",         "key: string, value",                   "object", "obj.add(\"age\", 30)"),
    ("object", "set",         "key: string, value",                   "object", "obj.set(\"name\", \"Alice\")"),
    ("object", "remove",      "key: string",                          "object", "obj.remove(\"temp\")"),
    ("object", "merge",       "other: object",                        "object", "obj1.merge(obj2) // other wins on clash"),
    // ── Blob ─────────────────────────────────────────────────────────────────
    ("blob",   "size",        "",                                     "int",    "myBlob.size() // byte count"),
    ("blob",   "mimeType",    "",                                     "string", "myBlob.mimeType() // → \"image/png\""),
    ("blob",   "toHex",       "",                                     "string", "myBlob.toHex()"),
    ("blob",   "isValid",     "",                                     "bool",   "myBlob.isValid()"),
    ("blob",   "toBytes",     "",                                     "array",  "myBlob.toBytes() // ints 0-255"),
    ("blob",   "slice",       "start: int, end: int",                 "blob",   "myBlob.slice(0, 100)"),
    // ── Regex ────────────────────────────────────────────────────────────────
    ("regex",  "test",        "text: string",                         "bool",   "r:(\"^\\\\d+$\").test(\"123\") // → true"),
    ("regex",  "match",       "text: string",                         "array",  "r.(\"(\\\\w+)\").match(\"hello\")"),
    ("regex",  "matchAll",    "text: string",                         "array",  "r:(\"\\\\d+\").matchAll(\"a1b2\")"),
    ("regex",  "replace",     "text: string, replacement: string",    "string", "r.(\"\\\\d\").replace(\"a1\", \"X\")"),
    ("regex",  "split",       "text: string",                         "array",  "r:(\"\\\\s+\").split(\"a b c\")"),
    ("regex",  "isValid",     "",                                     "bool",   "myRegex.isValid()"),
    // ── Timestamp ────────────────────────────────────────────────────────────
    ("timestamp", "format",        "pattern: string",  "string",    "ts.format(\"%Y-%m-%d %H:%M\")"),
    ("timestamp", "addDays",       "n: double",        "timestamp", "ts.addDays(7)"),
    ("timestamp", "addHours",      "n: double",        "timestamp", "ts.addHours(24)"),
    ("timestamp", "addMinutes",    "n: double",        "timestamp", "ts.addMinutes(30)"),
    ("timestamp", "addSeconds",    "n: double",        "timestamp", "ts.addSeconds(60)"),
    ("timestamp", "addMilliseconds","n: long",         "timestamp", "ts.addMilliseconds(500L)"),
    ("timestamp", "year",          "",                 "int",       "ts.year() // → 2025"),
    ("timestamp", "month",         "",                 "int",       "ts.month() // → 6"),
    ("timestamp", "day",           "",                 "int",       "ts.day() // → 15"),
    ("timestamp", "hour",          "",                 "int",       "ts.hour() // → 10"),
    ("timestamp", "minute",        "",                 "int",       "ts.minute() // → 30"),
    ("timestamp", "second",        "",                 "int",       "ts.second() // → 45"),
    ("timestamp", "millisecond",   "",                 "int",       "ts.millisecond() // → 0-999"),
    ("timestamp", "dayOfWeek",     "",                 "int",       "ts.dayOfWeek() // 0=Sun…6=Sat"),
    ("timestamp", "dayOfYear",     "",                 "int",       "ts.dayOfYear() // 1-366"),
    ("timestamp", "toUnixTime",    "",                 "long",      "ts.toUnixTime() // seconds since epoch"),
    ("timestamp", "toUnixMillis",  "",                 "long",      "ts.toUnixMillis() // millis since epoch"),
    // ── Date ─────────────────────────────────────────────────────────────────
    ("date",   "format",      "pattern: string",       "string",    "dt.format(\"%Y-%m-%d\")"),
    ("date",   "addDays",     "n: double",             "date",      "dt.addDays(7)"),
    ("date",   "year",        "",                      "int",       "dt.year() // → 2025"),
    ("date",   "month",       "",                      "int",       "dt.month() // → 6"),
    ("date",   "day",         "",                      "int",       "dt.day() // → 15"),
    ("date",   "dayOfWeek",   "",                      "int",       "dt.dayOfWeek() // 0=Sun…6=Sat"),
    ("date",   "dayOfYear",   "",                      "int",       "dt.dayOfYear() // 1-366"),
    ("date",   "toUnixTime",  "",                      "long",      "dt.toUnixTime()"),
    ("date",   "toString",    "",                      "string",    "dt.toString() // → \"2025-06-15\""),
];

// ── Static method signatures ──────────────────────────────────────────────────

/// Signatures for builtin static object methods.
/// (class_name, method_name, signature_str, description, example)
pub static STATIC_SIGS: &[(&str, &str, &str, &str, &str)] = &[
    // Math
    ("Math", "sqrt",      "Math.sqrt(x: double) → double",          "Square root. x must be ≥ 0.",                "Math.sqrt(16)          // → 4.0"),
    ("Math", "abs",       "Math.abs(x: number) → double",           "Absolute value.",                            "Math.abs(-42)          // → 42.0"),
    ("Math", "pow",       "Math.pow(base, exp: double) → double",   "base raised to exp.",                        "Math.pow(2, 10)        // → 1024.0"),
    ("Math", "floor",     "Math.floor(x: double) → int",            "Largest integer ≤ x.",                       "Math.floor(3.9)        // → 3"),
    ("Math", "ceil",      "Math.ceil(x: double) → int",             "Smallest integer ≥ x.",                      "Math.ceil(3.1)         // → 4"),
    ("Math", "round",     "Math.round(x: double) → double",         "Round to nearest integer.",                  "Math.round(3.5)        // → 4.0"),
    ("Math", "clamp",     "Math.clamp(v, min, max) → double",       "Clamp v so min ≤ result ≤ max.",             "Math.clamp(15,0,10)    // → 10.0"),
    ("Math", "pi",        "Math.pi() → double",                     "π ≈ 3.14159265358979",                       "Math.pi()"),
    ("Math", "e",         "Math.e() → double",                      "Euler's number e ≈ 2.71828",                 "Math.e()"),
    ("Math", "min",       "Math.min(a, b: number) → double",        "Smaller of two numbers.",                    "Math.min(3, 7)         // → 3.0"),
    ("Math", "max",       "Math.max(a, b: number) → double",        "Larger of two numbers.",                     "Math.max(3, 7)         // → 7.0"),
    ("Math", "sin",       "Math.sin(x: double) → double",           "Sine of angle in radians.",                  "Math.sin(0.0)          // → 0.0"),
    ("Math", "cos",       "Math.cos(x: double) → double",           "Cosine of angle in radians.",                "Math.cos(0.0)          // → 1.0"),
    ("Math", "tan",       "Math.tan(x: double) → double",           "Tangent of angle in radians.",               "Math.tan(0.0)          // → 0.0"),
    ("Math", "log",       "Math.log(x: double) → double",           "Natural logarithm (ln).",                    "Math.log(Math.e())     // → 1.0"),
    ("Math", "log10",     "Math.log10(x: double) → double",         "Base-10 logarithm.",                         "Math.log10(100.0)      // → 2.0"),
    ("Math", "sign",      "Math.sign(x: number) → int",             "Returns -1, 0, or 1.",                       "Math.sign(-5)          // → -1"),
    ("Math", "radians",   "Math.radians(degrees: double) → double", "Degrees to radians.",                        "Math.radians(180.0)    // → π"),
    ("Math", "degrees",   "Math.degrees(radians: double) → double", "Radians to degrees.",                        "Math.degrees(Math.pi()) // → 180.0"),
    ("Math", "truncate",  "Math.truncate(x: double) → double",      "Truncate toward zero.",                      "Math.truncate(3.9)     // → 3.0"),
    ("Math", "sqrt2",     "Math.sqrt2() → double",                  "√2 ≈ 1.41421356237",                         "Math.sqrt2()"),
    // DateTime
    ("DateTime", "now",           "DateTime.now() → timestamp",                    "Current UTC date-time.",                            "now = DateTime.now()"),
    ("DateTime", "today",         "DateTime.today() → date",                       "Today's date at midnight UTC.",                     "today = DateTime.today()"),
    ("DateTime", "utcNow",        "DateTime.utcNow() → timestamp",                 "Alias for now().",                                  "DateTime.utcNow()"),
    ("DateTime", "format",        "DateTime.format(ts, pat) → string",             "Format via strftime pattern.",                      "DateTime.format(DateTime.now(), \"%Y-%m-%d\")"),
    ("DateTime", "year",          "DateTime.year(d) → int",                        "Extract year from date/timestamp.",                 "DateTime.year(2025-06-15) // → 2025"),
    ("DateTime", "month",         "DateTime.month(d) → int",                       "Extract month (1–12).",                             "DateTime.month(2025-06-15) // → 6"),
    ("DateTime", "day",           "DateTime.day(d) → int",                         "Extract day of month.",                             "DateTime.day(2025-06-15) // → 15"),
    ("DateTime", "hour",          "DateTime.hour(ts) → int",                       "Extract hour (0–23).",                              "DateTime.hour(DateTime.now())"),
    ("DateTime", "minute",        "DateTime.minute(ts) → int",                     "Extract minute (0–59).",                            "DateTime.minute(DateTime.now())"),
    ("DateTime", "second",        "DateTime.second(ts) → int",                     "Extract second (0–59).",                            "DateTime.second(DateTime.now())"),
    ("DateTime", "addDays",       "DateTime.addDays(d, n: int) → date",            "Add n days to a date.",                             "DateTime.addDays(2025-01-01, 30)"),
    ("DateTime", "addMonths",     "DateTime.addMonths(d, n: int) → date",          "Add n months.",                                     "DateTime.addMonths(2025-01-01, 3)"),
    ("DateTime", "addYears",      "DateTime.addYears(d, n: int) → date",           "Add n years.",                                      "DateTime.addYears(2025-01-01, 1)"),
    ("DateTime", "subtract",      "DateTime.subtract(a, b) → double",              "Difference in days between two dates.",             "DateTime.subtract(2025-06-15, 2025-01-01)"),
    ("DateTime", "isLeapYear",    "DateTime.isLeapYear(y: int) → bool",            "True if year is a leap year.",                      "DateTime.isLeapYear(2024) // → true"),
    ("DateTime", "dayOfWeek",     "DateTime.dayOfWeek(d) → int",                   "Day of week (0=Sun, 6=Sat).",                        "DateTime.dayOfWeek(2025-06-15)"),
    ("DateTime", "fromUnixTime",  "DateTime.fromUnixTime(secs: long) → timestamp", "Unix epoch seconds to timestamp.",                  "DateTime.fromUnixTime(0L)"),
    ("DateTime", "toUnixTime",    "DateTime.toUnixTime(ts) → long",                "Timestamp to Unix epoch seconds.",                  "DateTime.toUnixTime(DateTime.now())"),
    // Array (static factory)
    ("Array", "range",    "Array.range(start, end: int) → array",  "Integers from start to end inclusive.",   "Array.range(1, 5) // → [1,2,3,4,5]"),
    ("Array", "fill",     "Array.fill(val, count: int) → array",   "Repeat val count times.",                 "Array.fill(0, 3) // → [0,0,0]"),
    ("Array", "empty",    "Array.empty() → array",                  "Create an empty array.",                  "Array.empty()    // → []"),
    ("Array", "of",       "Array.of(...vals) → array",              "Create array from listed values.",        "Array.of(1, 2, 3)"),
    ("Array", "repeat",   "Array.repeat(val, n: int) → array",      "Alias for fill.",                         "Array.repeat(\"x\", 3)"),
    ("Array", "sum",      "Array.sum(arr: array) → double",         "Sum of numeric elements.",                "Array.sum([1,2,3]) // → 6.0"),
    ("Array", "min",      "Array.min(arr: array) → double",         "Minimum numeric value.",                  "Array.min([3,1,2]) // → 1.0"),
    ("Array", "max",      "Array.max(arr: array) → double",         "Maximum numeric value.",                  "Array.max([3,1,2]) // → 3.0"),
    ("Array", "sort",     "Array.sort(arr: array) → array",         "Return sorted copy.",                     "Array.sort([3,1,2])"),
    ("Array", "unique",   "Array.unique(arr: array) → array",       "Remove duplicates.",                      "Array.unique([1,1,2])"),
    ("Array", "flatten",  "Array.flatten(arr: array) → array",      "Flatten one level of nesting.",           "Array.flatten([[1,2],[3]])"),
    ("Array", "average",  "Array.average(arr: array) → double",     "Average of numeric elements.",            "Array.average([1,2,3]) // → 2.0"),
    // Random
    ("Random", "range",          "Random.range(min, max: int) → int",           "Random int in [min,max].",           "Random.range(1, 6)"),
    ("Random", "longRange",      "Random.longRange(min, max: long) → long",     "Random long in range.",              "Random.longRange(0L, 1_000_000L)"),
    ("Random", "nextFloat",      "Random.nextFloat() → float",                  "Random float in [0,1).",             "Random.nextFloat()"),
    ("Random", "nextDouble",     "Random.nextDouble() → double",                "Random double in [0,1).",            "Random.nextDouble()"),
    ("Random", "nextBool",       "Random.nextBool() → bool",                    "Random boolean.",                    "Random.nextBool()"),
    ("Random", "floatRange",     "Random.floatRange(min, max: float) → float",  "Random float in range.",             "Random.floatRange(0.0f, 1.0f)"),
    ("Random", "doubleRange",    "Random.doubleRange(min, max: double) → double","Random double in range.",            "Random.doubleRange(0.0, 1.0)"),
    ("Random", "choice",         "Random.choice(arr: array) → any",             "Random element from array.",         "Random.choice([\"a\",\"b\",\"c\"])"),
    ("Random", "shuffle",        "Random.shuffle(arr: array) → array",          "Return shuffled copy.",              "Random.shuffle([1,2,3,4])"),
    ("Random", "alphanumeric",   "Random.alphanumeric(len: int) → string",      "Random alphanumeric string.",        "Random.alphanumeric(8)"),
    ("Random", "randomString",   "Random.randomString(len: int) → string",      "Alias for alphanumeric.",            "Random.randomString(12)"),
    // Guid
    ("Guid", "new",      "Guid.new() → string",                 "Generate a UUID v4 string.",               "id = Guid.new()"),
    ("Guid", "parse",    "Guid.parse(str) → string",            "Parse GUID; throws on invalid.",           "Guid.parse(\"550e8400-...\")"),
    ("Guid", "validate", "Guid.validate(str) → bool",           "Check if string is a valid GUID.",         "Guid.validate(\"550e8400-...\") // → true"),
    ("Guid", "empty",    "Guid.empty() → string",               "All-zero GUID.",                           "Guid.empty()"),
    ("Guid", "format",   "Guid.format(guid, fmt) → string",     "Format GUID with braces or hyphens.",      "Guid.format(Guid.new(), \"D\")"),
    // IpAddress
    ("IpAddress", "parse",       "IpAddress.parse(str) → string",      "Parse IP; throws on invalid.",           "IpAddress.parse(\"192.168.1.1\")"),
    ("IpAddress", "validate",    "IpAddress.validate(str) → bool",     "Check valid IPv4 or IPv6.",              "IpAddress.validate(\"10.0.0.1\")"),
    ("IpAddress", "isV4",        "IpAddress.isV4(str) → bool",         "True if IPv4.",                          "IpAddress.isV4(\"127.0.0.1\")"),
    ("IpAddress", "isV6",        "IpAddress.isV6(str) → bool",         "True if IPv6.",                          "IpAddress.isV6(\"::1\") // → true"),
    ("IpAddress", "isPrivate",   "IpAddress.isPrivate(str) → bool",    "True for RFC-1918 ranges.",              "IpAddress.isPrivate(\"192.168.1.1\")"),
    ("IpAddress", "isLoopback",  "IpAddress.isLoopback(str) → bool",   "True if loopback address.",              "IpAddress.isLoopback(\"127.0.0.1\")"),
    ("IpAddress", "localhost",   "IpAddress.localhost() → string",      "Returns \"127.0.0.1\".",                 "IpAddress.localhost()"),
    ("IpAddress", "anyAddress",  "IpAddress.anyAddress() → string",     "Returns \"0.0.0.0\".",                   "IpAddress.anyAddress()"),
    // Dix
    ("Dix", "Log",        "Dix.Log(message: any) → void",       "Log at INFO level.",           "Dix.Log(\"Building \" + name)"),
    ("Dix", "LogInfo",    "Dix.LogInfo(message: any) → void",   "Log at INFO level.",           "Dix.LogInfo(\"ok\")"),
    ("Dix", "LogWarning", "Dix.LogWarning(message: any) → void","Log at WARNING level.",        "Dix.LogWarning(\"slow\")"),
    ("Dix", "LogError",   "Dix.LogError(message: any) → void",  "Log at ERROR level.",          "Dix.LogError(\"failed\")"),
    ("Dix", "LogDebug",   "Dix.LogDebug(message: any) → void",  "Log at DEBUG level.",          "Dix.LogDebug(\"x=\" + x)"),
    ("Dix", "Assert",     "Dix.Assert(cond, msg) → void",        "Abort if condition is false.", "Dix.Assert(health > 0, \"positive\")"),
    ("Dix", "Format",     "Dix.Format(tmpl, ...args) → string",  "Format with positional args.", "Dix.Format(\"{0}:{1}\", host, port)"),
    ("Dix", "Join",       "Dix.Join(sep, ...vals) → string",     "Join values with separator.",  "Dix.Join(\",\", \"a\", \"b\", \"c\")"),
    // Enum
    ("Enum", "getValues",   "Enum.getValues(name) → array",          "All field names of an enum.",           "Enum.getValues(\"Difficulty\")"),
    ("Enum", "getName",     "Enum.getName(name,val) → string",        "Field name for an integer value.",      "Enum.getName(\"Difficulty\", 2)"),
    ("Enum", "getValue",    "Enum.getValue(name,field) → int",        "Integer value for a field name.",       "Enum.getValue(\"Difficulty\", \"HARD\")"),
    ("Enum", "count",       "Enum.count(name) → int",                 "Number of fields in an enum.",          "Enum.count(\"Difficulty\")"),
    ("Enum", "exists",      "Enum.exists(name) → bool",               "True if enum name is declared.",        "Enum.exists(\"Difficulty\")"),
    ("Enum", "list",        "Enum.list() → array",                    "Names of all declared enums.",          "Enum.list()"),
    ("Enum", "min",         "Enum.min(name) → int",                   "Minimum integer value in enum.",        "Enum.min(\"Difficulty\")"),
    ("Enum", "max",         "Enum.max(name) → int",                   "Maximum integer value in enum.",        "Enum.max(\"Difficulty\")"),
    ("Enum", "toArray",     "Enum.toArray(name) → array",             "Array of {name, value} objects.",       "Enum.toArray(\"Difficulty\")"),
    ("Enum", "contains",    "Enum.contains(name, val: int) → bool",   "True if integer value exists in enum.", "Enum.contains(\"Difficulty\", 2)"),
    ("Enum", "random",      "Enum.random(name) → int",                "Random value from enum.",               "Enum.random(\"Difficulty\")"),
];
