"""
Type stubs for the midmanstudio.mdix native extension.
These stubs enable IDE autocompletion and mypy type checking.
"""

from __future__ import annotations

from typing import Any, Callable, List, Optional, Tuple, Union

# ── MdixError ──────────────────────────────────────────────────────────────────

class MdixError(Exception):
    """Raised when any DixScript operation fails."""
    ...

# ── MdixResult ─────────────────────────────────────────────────────────────────

class MdixResult:
    """
    Railway-oriented result type.

    Use ``bool(result)`` to check success.
    Use ``.value`` / ``.error`` to access the content.
    """

    @classmethod
    def ok(cls, value: Any) -> MdixResult: ...
    @classmethod
    def err(cls, message: str) -> MdixResult: ...

    @property
    def is_success(self) -> bool: ...
    @property
    def is_failure(self) -> bool: ...
    @property
    def value(self) -> Any: ...
    @property
    def error(self) -> str: ...

    def or_raise(self) -> Any: ...
    def unwrap(self) -> Any: ...
    def unwrap_or(self, fallback: Any) -> Any: ...
    def unwrap_or_else(self, factory: Callable[[str], Any]) -> Any: ...

    def map(self, f: Callable[[Any], Any]) -> MdixResult: ...
    def and_then(self, f: Callable[[Any], MdixResult]) -> MdixResult: ...
    def ensure(
        self,
        predicate: Callable[[Any], bool],
        error_message: str,
    ) -> MdixResult: ...
    def or_(self, fallback: MdixResult) -> MdixResult: ...
    def fold(
        self,
        on_success: Callable[[Any], Any],
        on_failure: Callable[[str], Any],
    ) -> Any: ...
    def tap(self, f: Callable[[Any], None]) -> MdixResult: ...
    def tap_error(self, f: Callable[[str], None]) -> MdixResult: ...

    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __class_getitem__(cls, item: Any) -> Any: ...

# ── MdixDatabase ───────────────────────────────────────────────────────────────

class MdixDatabase:
    """Loaded DixScript database. Use as a context manager for automatic cleanup."""

    def __enter__(self) -> MdixDatabase: ...
    def __exit__(
        self,
        exc_type: Any,
        exc_val: Any,
        exc_tb: Any,
    ) -> bool: ...

    def close(self) -> None: ...
    def free(self) -> None: ...

    @property
    def is_valid(self) -> bool: ...
    @property
    def entry_count(self) -> int: ...

    # ── Loading — raising ─────────────────────────────────────────────────────

    @staticmethod
    def load(path: str) -> MdixDatabase: ...
    @staticmethod
    def load_str(source: str) -> MdixDatabase: ...
    @staticmethod
    def from_json(json: str) -> MdixDatabase: ...
    @staticmethod
    def from_toml(toml: str) -> MdixDatabase: ...
    @staticmethod
    def load_encrypted(
        enc_path: str,
        key_path: Optional[str] = None,
    ) -> MdixDatabase: ...
    @staticmethod
    def load_encrypted_password(enc_path: str, password: str) -> MdixDatabase: ...

    # ── Loading — railway ─────────────────────────────────────────────────────

    @staticmethod
    def try_load(path: str) -> MdixResult: ...
    @staticmethod
    def try_load_str(source: str) -> MdixResult: ...
    @staticmethod
    def try_from_json(json: str) -> MdixResult: ...
    @staticmethod
    def try_from_toml(toml: str) -> MdixResult: ...

    # ── Inspection ────────────────────────────────────────────────────────────

    def exists(self, path: str) -> bool: ...
    def get_type(self, path: str) -> str: ...
    def get_array_length(self, path: str) -> int: ...
    def get_keys(self, prefix: str = "") -> List[str]: ...

    # ── Typed getters — raising ───────────────────────────────────────────────

    def get_string(
        self, path: str, default: Optional[str] = None
    ) -> str: ...
    def get_int(
        self, path: str, default: Optional[int] = None
    ) -> int: ...
    def get_long(
        self, path: str, default: Optional[int] = None
    ) -> int: ...
    def get_float(
        self, path: str, default: Optional[float] = None
    ) -> float: ...
    def get_double(
        self, path: str, default: Optional[float] = None
    ) -> float: ...
    def get_bool(
        self, path: str, default: Optional[bool] = None
    ) -> bool: ...
    def get_json(self, path: str) -> str: ...
    def get_enum_name(self, path: str) -> str: ...
    def get_enum_field(self, path: str) -> str: ...

    # ── Typed getters — railway ───────────────────────────────────────────────

    def try_get_string(self, path: str) -> MdixResult: ...
    def try_get_int(self, path: str) -> MdixResult: ...
    def try_get_long(self, path: str) -> MdixResult: ...
    def try_get_float(self, path: str) -> MdixResult: ...
    def try_get_double(self, path: str) -> MdixResult: ...
    def try_get_bool(self, path: str) -> MdixResult: ...
    def try_get_json(self, path: str) -> MdixResult: ...

    # ── Export ────────────────────────────────────────────────────────────────

    def to_json(self, indented: bool = True) -> str: ...
    def to_toml(self) -> str: ...
    def to_mdix(self) -> str: ...
    def to_table(self) -> Any:
        """Whole database as native Python dict/list structure."""
        ...
    @staticmethod
    def from_table(table: Any) -> MdixDatabase:
        """Reverse of `to_table()` — build a database from a dict/list."""
        ...

    # ── Schema / merge ───────────────────────────────────────────────────────

    def validate_schema(self, schema: "MdixSchemaBuilder") -> MdixValidationReport: ...
    def merge_with(
        self,
        other: MdixDatabase,
        strategy: Optional[str] = None,
        array_strategy: Optional[str] = None,
        temp_dir: Optional[str] = None,
    ) -> Tuple[MdixDatabase, List[Any]]: ...

    # ── Querying ──────────────────────────────────────────────────────────────

    def query(self, path: str) -> Optional["MdixQuery"]:
        """LINQ-style chainable query over the array at `path`.

        `None` if `path` doesn't exist or isn't an array.
        """
        ...
    def query_many(self, pattern: str) -> "MdixQuery":
        """Query across sibling paths matched by a `*`-wildcarded `pattern`."""
        ...

    def __repr__(self) -> str: ...

# ── MdixBuilder ────────────────────────────────────────────────────────────────

class MdixBuilder:
    """
    Programmatic `.mdix` builder.

    Two-tier ordering is enforced: all ``set_*`` (tier-1 flat) calls
    must come before any ``with_*`` (tier-2 grouped) calls.
    Violating this raises ``MdixError`` immediately.
    """

    def __repr__(self) -> str: ...

    # ── @CONFIG ───────────────────────────────────────────────────────────────

    def set_config(self, key: str, value: str) -> MdixBuilder: ...
    def add_enum(self, name: str, fields: List[Any]) -> MdixBuilder: ...

    # ── @DATA tier 1 ─────────────────────────────────────────────────────────

    def set_string(self, path: str, value: str) -> MdixBuilder: ...
    def set_int(self, path: str, value: int) -> MdixBuilder: ...
    def set_float(self, path: str, value: float) -> MdixBuilder: ...
    def set_double(self, path: str, value: float) -> MdixBuilder: ...
    def set_bool(self, path: str, value: bool) -> MdixBuilder: ...
    def set_date(self, path: str, value: str) -> MdixBuilder: ...
    def set_timestamp(self, path: str, value: str) -> MdixBuilder: ...
    def set_hex_color(self, path: str, value: str) -> MdixBuilder: ...
    def set_blob(self, path: str, base64_data: str) -> MdixBuilder: ...
    def set_regex(self, path: str, pattern: str) -> MdixBuilder: ...
    def set_enum(
        self, path: str, enum_name: str, field_name: str
    ) -> MdixBuilder: ...
    def set_array(self, path: str, items: List[Any]) -> MdixBuilder: ...
    def set_tuple(self, path: str, items: List[Any]) -> MdixBuilder: ...
    def set_object(self, path: str, props: dict) -> MdixBuilder: ...

    # ── @DATA tier 2 ─────────────────────────────────────────────────────────

    def with_table_properties(
        self,
        path: str,
        props: Optional[dict] = None,
        **kwargs: Any,
    ) -> MdixBuilder: ...
    def with_group_array(
        self, path: str, items: List[Any]
    ) -> MdixBuilder: ...

    # ── Internal (ML layer) ───────────────────────────────────────────────────

    def _with_raw_table_properties(
        self,
        path: str,
        raw_props: List[Tuple[str, str]],
    ) -> MdixBuilder: ...

    # ── Finalization ──────────────────────────────────────────────────────────

    def serialize(self) -> str: ...
    def to_database(self) -> MdixDatabase: ...
    def try_to_database(self) -> MdixResult: ...
    def reset_grouped(self) -> None: ...
    def reset(self) -> None: ...

# ── MdixMerger ─────────────────────────────────────────────────────────────────

class MdixMerger:
    """
    Merge two or more `.mdix` sources at the AST level.

    Strategy strings
    ----------------
    Conflict strategy (``with_strategy``):
        ``"weighted_priority"``  — higher-weight source wins (default)
        ``"primary_wins"``       — first source always wins conflicts
        ``"secondary_wins"``     — last source always wins conflicts
        ``"throw_on_conflict"``  — raises ``MdixError`` on any conflict

    Array strategy (``with_array_strategy``):
        ``"replace"``            — one source's array replaces the other
        ``"concat"``             — arrays are joined (duplicates kept)
        ``"concat_dedup"``       — arrays are joined and deduplicated (default)

    Example::

        db = (MdixMerger()
              .with_strategy("primary_wins")
              .merge_strings([
                  ("base",    '@DATA( name = "App" )', 1.0),
                  ("overlay", '@DATA( name = "Alt"  )', 0.5),
              ]))
        # db.get_string("name") == "App"
    """

    def __repr__(self) -> str: ...

    def with_strategy(self, strategy: str) -> MdixMerger: ...
    def with_array_strategy(self, strategy: str) -> MdixMerger: ...

    def merge_files(self, paths: List[str]) -> MdixDatabase: ...
    def merge_files_weighted(
        self, paths_and_weights: List[Tuple[str, float]]
    ) -> MdixDatabase: ...

    def try_merge_files(self, paths: List[str]) -> MdixResult: ...
    def try_merge_files_weighted(
        self, paths_and_weights: List[Tuple[str, float]]
    ) -> MdixResult: ...

    def merge_strings(
        self,
        sources: List[Tuple[str, str, float]],
    ) -> MdixDatabase:
        """
        Merge `.mdix` source text directly without touching disk.

        ``sources`` is a list of ``(label, source_text, weight)`` triples.
        ``label`` is used only in conflict-report messages.
        """
        ...

# ── MdixValidationError ────────────────────────────────────────────────────────

class MdixValidationError:
    """A single field-level validation failure from ``MdixSchemaBuilder.validate``."""

    @property
    def path(self) -> str:
        """Dotted path of the failing field."""
        ...
    @property
    def expected(self) -> str:
        """What the schema expected (type name or description)."""
        ...
    @property
    def actual(self) -> str:
        """What was actually found (type name or ``"missing"``)."""
        ...
    @property
    def kind(self) -> str:
        """One of ``"missing"``, ``"wrong_type"``, ``"invalid_value"``."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── MdixValidationReport ───────────────────────────────────────────────────────

class MdixValidationReport:
    """
    Result of a schema validation pass. Never raises — always returned.

    Use ``bool(report)`` or ``report.is_valid`` to check the outcome::

        report = schema.validate(db)
        if not report:
            for err in report.errors:
                print(err)
    """

    @property
    def is_valid(self) -> bool: ...
    @property
    def error_count(self) -> int: ...
    @property
    def errors(self) -> List[MdixValidationError]: ...

    def failed_paths(self) -> List[str]: ...
    def errors_of_kind(self, kind: str) -> List[MdixValidationError]: ...

    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── MdixSchemaBuilder ──────────────────────────────────────────────────────────

class MdixSchemaBuilder:
    """
    Fluent schema definition and validation.

    The same schema instance can be reused across multiple ``validate()``
    calls — it borrows, not consumes.

    Accepted type strings for ``require`` / ``optional``:
        ``"string"``, ``"int"``, ``"long"``, ``"float"``, ``"double"``,
        ``"bool"``, ``"array"``, ``"object"``, ``"date"``, ``"timestamp"``,
        ``"hexcolor"``, ``"blob"``, ``"regex"``, ``"enum"``, ``"any"``

    Example::

        schema = (MdixSchemaBuilder()
                  .require_string("app_name")
                  .require_int("port")
                  .optional_bool("debug"))

        for db in [db_prod, db_staging]:
            report = schema.validate(db)
            if not report.is_valid:
                print(report)
    """

    @property
    def field_count(self) -> int: ...
    @property
    def paths(self) -> List[str]: ...

    # ── require — field must be present with the given type ───────────────────

    def require(self, path: str, expected_type: str) -> MdixSchemaBuilder: ...
    def require_string(self, path: str) -> MdixSchemaBuilder: ...
    def require_int(self, path: str) -> MdixSchemaBuilder: ...
    def require_long(self, path: str) -> MdixSchemaBuilder: ...
    def require_float(self, path: str) -> MdixSchemaBuilder: ...
    def require_double(self, path: str) -> MdixSchemaBuilder: ...
    def require_bool(self, path: str) -> MdixSchemaBuilder: ...
    def require_array(self, path: str) -> MdixSchemaBuilder: ...
    def require_object(self, path: str) -> MdixSchemaBuilder: ...
    def require_enum(self, path: str) -> MdixSchemaBuilder: ...

    # ── optional — field may be absent; if present, type must match ───────────

    def optional(self, path: str, expected_type: str) -> MdixSchemaBuilder: ...
    def optional_string(self, path: str) -> MdixSchemaBuilder: ...
    def optional_int(self, path: str) -> MdixSchemaBuilder: ...
    def optional_long(self, path: str) -> MdixSchemaBuilder: ...
    def optional_float(self, path: str) -> MdixSchemaBuilder: ...
    def optional_double(self, path: str) -> MdixSchemaBuilder: ...
    def optional_bool(self, path: str) -> MdixSchemaBuilder: ...
    def optional_array(self, path: str) -> MdixSchemaBuilder: ...
    def optional_object(self, path: str) -> MdixSchemaBuilder: ...

    # ── Metadata ──────────────────────────────────────────────────────────────

    def with_description(self, description: str) -> MdixSchemaBuilder: ...

    # ── Validation ────────────────────────────────────────────────────────────

    def validate(self, db: MdixDatabase) -> MdixValidationReport: ...

# ── MdixWatcher ────────────────────────────────────────────────────────────────

class MdixWatcher:
    """
    Poll-based hot reload for a `.mdix` file. Call `.check()` from your own
    update loop / tick / timer callback — there's no background thread or
    OS filesystem-event integration here, by design (see `watch.rs`).

    Example::

        watcher = MdixWatcher("config.mdix")

        # in your update loop:
        db, changed = watcher.check()
        if changed:
            apply_new_config(db)
    """

    def __init__(self, path: str) -> None: ...

    def check(self) -> Tuple[Optional[MdixDatabase], bool]:
        """
        Reloads only if the watched file's modified-time has changed since
        the last successful check (or since construction, on the first
        call). Returns `(database_or_none, changed)` — `database` is
        `None` when `changed` is `False`.
        """
        ...
    def force_reload(self) -> MdixDatabase:
        """Reloads unconditionally, regardless of whether the file changed."""
        ...
    def has_changed(self) -> bool:
        """Checks whether the file has changed without reloading it."""
        ...

    @property
    def has_loaded(self) -> bool:
        """`True` once a successful reload has happened at least once."""
        ...
    @property
    def path(self) -> str: ...

    def __repr__(self) -> str: ...

# ── MdixQuery ──────────────────────────────────────────────────────────────────

class MdixQuery:
    """
    LINQ-style chainable query over native Python data — returned by
    `MdixDatabase.query()` / `MdixDatabase.query_many()`. Every
    predicate/key/selector is a plain Python callable.

    Example::

        high_priority = (db.query("tasks")
            .where_(lambda t: t["priority"] == 3)
            .order_by_desc(lambda t: t["priority"]))
        names = high_priority.select(lambda t: t["name"])
    """

    def __init__(self, items: List[Any]) -> None: ...

    # ── filtering / projection ──────────────────────────────────────────────

    def where_(self, predicate: Callable[[Any], bool]) -> MdixQuery: ...
    def where_field_eq(self, field: str, value: Any) -> MdixQuery: ...
    def skip(self, n: int) -> MdixQuery: ...
    def take(self, n: int) -> MdixQuery: ...
    def distinct(self) -> MdixQuery: ...
    def select(self, map: Callable[[Any], Any]) -> List[Any]: ...
    def select_field(self, name: str) -> List[Any]: ...

    # ── ordering ─────────────────────────────────────────────────────────────

    def order_by(self, key: Callable[[Any], Any]) -> MdixQuery: ...
    def order_by_desc(self, key: Callable[[Any], Any]) -> MdixQuery: ...

    # ── grouping ─────────────────────────────────────────────────────────────

    def group_by(
        self, key: Callable[[Any], Any]
    ) -> List[Tuple[Any, List[Any]]]: ...

    # ── terminal predicates / aggregates ────────────────────────────────────

    def any(self, predicate: Callable[[Any], bool]) -> bool: ...
    def all(self, predicate: Callable[[Any], bool]) -> bool: ...
    def count(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def first(self) -> Optional[Any]: ...
    def first_or(self, default: Any) -> Any: ...
    def last(self) -> Optional[Any]: ...
    def nth(self, index: int) -> Optional[Any]: ...
    def sum_int(self) -> int: ...
    def sum_float(self) -> float: ...
    def avg_float(self) -> Optional[float]: ...
    def min_by_key(self, key: Callable[[Any], Any]) -> Optional[Any]: ...
    def max_by_key(self, key: Callable[[Any], Any]) -> Optional[Any]: ...
    def to_list(self) -> List[Any]: ...

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

# ── Module-level ───────────────────────────────────────────────────────────────

__version__: str
