"""
Type stubs for the midmanstudio.mdix native extension.
These stubs enable IDE autocompletion and mypy type checking.
"""

from __future__ import annotations

from typing import Any, Callable, List, Optional, Tuple, Union

# ── MdixError ──────────────────────────────────────────────────────────────────

class MdixError(Exception):
    """Raised when any DixScript operation fails."""
    ...

# ── MdixResult ──────────────────────────────────────────────────────────────────

class MdixResult:
    """
    Railway-oriented result type.

    Use ``bool(result)`` to check success.
    Use ``.value`` / ``.error`` to access the content.
    """

    @classmethod
    def ok(cls, value: Any) -> MdixResult: ...
    @classmethod
    def err(cls, message: str) -> MdixResult: ...

    @property
    def is_success(self) -> bool: ...
    @property
    def is_failure(self) -> bool: ...
    @property
    def value(self) -> Any: ...
    @property
    def error(self) -> str: ...

    def or_raise(self) -> Any: ...
    def unwrap(self) -> Any: ...
    def unwrap_or(self, fallback: Any) -> Any: ...
    def unwrap_or_else(self, factory: Callable[[str], Any]) -> Any: ...

    def map(self, f: Callable[[Any], Any]) -> MdixResult: ...
    def and_then(self, f: Callable[[Any], MdixResult]) -> MdixResult: ...
    def ensure(
        self,
        predicate: Callable[[Any], bool],
        error_message: str,
    ) -> MdixResult: ...
    def or_(self, fallback: MdixResult) -> MdixResult: ...
    def fold(
        self,
        on_success: Callable[[Any], Any],
        on_failure: Callable[[str], Any],
    ) -> Any: ...
    def tap(self, f: Callable[[Any], None]) -> MdixResult: ...
    def tap_error(self, f: Callable[[str], None]) -> MdixResult: ...

    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __class_getitem__(cls, item: Any) -> Any: ...

# ── MdixDatabase ───────────────────────────────────────────────────────────────

class MdixDatabase:
    """Loaded DixScript database. Use as a context manager for automatic cleanup."""

    def __enter__(self) -> MdixDatabase: ...
    def __exit__(
        self,
        exc_type: Any,
        exc_val: Any,
        exc_tb: Any,
    ) -> bool: ...

    def close(self) -> None: ...
    def free(self) -> None: ...

    @property
    def is_valid(self) -> bool: ...
    @property
    def entry_count(self) -> int: ...

    # ── Loading — raising ────────────────────────────────────────────────────

    @staticmethod
    def load(path: str) -> MdixDatabase: ...
    @staticmethod
    def load_str(source: str) -> MdixDatabase: ...
    @staticmethod
    def from_json(json: str) -> MdixDatabase: ...
    @staticmethod
    def from_toml(toml: str) -> MdixDatabase: ...
    @staticmethod
    def load_encrypted(
        enc_path: str,
        key_path: Optional[str] = None,
    ) -> MdixDatabase: ...
    @staticmethod
    def load_encrypted_password(enc_path: str, password: str) -> MdixDatabase: ...

    # ── Loading — railway ────────────────────────────────────────────────────

    @staticmethod
    def try_load(path: str) -> MdixResult: ...
    @staticmethod
    def try_load_str(source: str) -> MdixResult: ...
    @staticmethod
    def try_from_json(json: str) -> MdixResult: ...
    @staticmethod
    def try_from_toml(toml: str) -> MdixResult: ...

    # ── Inspection ───────────────────────────────────────────────────────────

    def exists(self, path: str) -> bool: ...
    def get_type(self, path: str) -> str: ...
    def get_array_length(self, path: str) -> int: ...
    def get_keys(self, prefix: str = "") -> List[str]: ...

    # ── Typed getters — raising ───────────────────────────────────────────────

    def get_string(
        self, path: str, default: Optional[str] = None
    ) -> str: ...
    def get_int(
        self, path: str, default: Optional[int] = None
    ) -> int: ...
    def get_float(
        self, path: str, default: Optional[float] = None
    ) -> float: ...
    def get_double(
        self, path: str, default: Optional[float] = None
    ) -> float: ...
    def get_bool(
        self, path: str, default: Optional[bool] = None
    ) -> bool: ...
    def get_json(self, path: str) -> str: ...
    def get_enum_name(self, path: str) -> str: ...
    def get_enum_field(self, path: str) -> str: ...

    # ── Typed getters — railway ───────────────────────────────────────────────

    def try_get_string(self, path: str) -> MdixResult: ...
    def try_get_int(self, path: str) -> MdixResult: ...
    def try_get_float(self, path: str) -> MdixResult: ...
    def try_get_double(self, path: str) -> MdixResult: ...
    def try_get_bool(self, path: str) -> MdixResult: ...
    def try_get_json(self, path: str) -> MdixResult: ...

    # ── Export ────────────────────────────────────────────────────────────────

    def to_json(self, indented: bool = True) -> str: ...
    def to_toml(self) -> str: ...
    def to_mdix(self) -> str: ...
    def __repr__(self) -> str: ...

# ── MdixBuilder ────────────────────────────────────────────────────────────────

class MdixBuilder:
    """
    Programmatic `.mdix` builder.

    Two-tier ordering is enforced: all ``set_*`` (tier-1 flat) calls
    must come before any ``with_*`` (tier-2 grouped) calls.
    Violating this raises ``MdixError`` immediately.
    """

    def __repr__(self) -> str: ...

    # ── @CONFIG ───────────────────────────────────────────────────────────────

    def set_config(self, key: str, value: str) -> MdixBuilder: ...
    def add_enum(self, name: str, fields: List[Any]) -> MdixBuilder: ...

    # ── @DATA tier 1 ─────────────────────────────────────────────────────────

    def set_string(self, path: str, value: str) -> MdixBuilder: ...
    def set_int(self, path: str, value: int) -> MdixBuilder: ...
    def set_float(self, path: str, value: float) -> MdixBuilder: ...
    def set_double(self, path: str, value: float) -> MdixBuilder: ...
    def set_bool(self, path: str, value: bool) -> MdixBuilder: ...
    def set_date(self, path: str, value: str) -> MdixBuilder: ...
    def set_timestamp(self, path: str, value: str) -> MdixBuilder: ...
    def set_hex_color(self, path: str, value: str) -> MdixBuilder: ...
    def set_blob(self, path: str, base64_data: str) -> MdixBuilder: ...
    def set_regex(self, path: str, pattern: str) -> MdixBuilder: ...
    def set_enum(
        self, path: str, enum_name: str, field_name: str
    ) -> MdixBuilder: ...
    def set_array(self, path: str, items: List[Any]) -> MdixBuilder: ...
    def set_tuple(self, path: str, items: List[Any]) -> MdixBuilder: ...
    def set_object(self, path: str, props: dict) -> MdixBuilder: ...

    # ── @DATA tier 2 ─────────────────────────────────────────────────────────

    def with_table_properties(
        self,
        path: str,
        props: Optional[dict] = None,
        **kwargs: Any,
    ) -> MdixBuilder: ...
    def with_group_array(
        self, path: str, items: List[Any]
    ) -> MdixBuilder: ...

    # ── Internal (ML layer) ───────────────────────────────────────────────────

    def _with_raw_table_properties(
        self,
        path: str,
        raw_props: List[Tuple[str, str]],
    ) -> MdixBuilder: ...

    # ── Finalization ──────────────────────────────────────────────────────────

    def serialize(self) -> str: ...
    def to_database(self) -> MdixDatabase: ...
    def try_to_database(self) -> MdixResult: ...
    def reset_grouped(self) -> None: ...
    def reset(self) -> None: ...

# ── Module-level ───────────────────────────────────────────────────────────────

__version__: str
