using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace MidManStudio.Mdix.Core
{
    /// <summary>
    /// Generates real, type-safe C# <c>enum</c> declarations from a <c>.mdix</c> file's
    /// <c>@ENUMS</c> section, so DixScript enum data can be deserialized straight into
    /// proper C# enum-typed properties (see <see cref="MdixSerializer"/>'s enum support)
    /// instead of being read back as raw ints and hand-mapped.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is a pure C#, source-text-level implementation. It does not go through
    /// <c>mdix-ffi</c> or require loading the file into a native handle first (beyond a
    /// single call to <see cref="MdixConverter.StripComments"/> to remove comments before
    /// scanning), so it works even for a file that can't currently be loaded for unrelated
    /// reasons -- e.g. a missing decryption key -- as long as the <c>@ENUMS</c> section
    /// itself is well-formed.
    /// </para>
    /// <para>
    /// Field-value resolution intentionally does <b>not</b> compute values itself.
    /// DixScript's own resolver (see <c>enums_section_analyzer.rs</c> in the core crate)
    /// assigns each field without an explicit <c>= value</c> the previous field's resolved
    /// value plus one, starting from 0 -- and that is <i>exactly</i> C#'s native enum
    /// auto-numbering rule (<c>enum E { A, B, C = 5, D }</c> already gives A=0, B=1, C=5,
    /// D=6 in plain C#). So this generator only needs to preserve which fields had an
    /// explicit value and which didn't; the C# compiler that later builds the generated
    /// file reproduces the exact same numbers DixScript would, with no arithmetic
    /// duplicated here to drift out of sync.
    /// </para>
    /// <para>
    /// The generated enum type names match the DixScript enum names exactly (by
    /// convention, not configuration) -- this is the same convention
    /// <see cref="MdixSerializer"/> relies on when serializing an enum-typed property
    /// back to DixScript (<c>MdixSerializer</c> uses the C# type's own <c>Name</c> as the
    /// DixScript enum name), so a type generated by this class round-trips through
    /// <c>Serialize</c>/<c>Deserialize</c> without any extra wiring.
    /// </para>
    /// </remarks>
    public static class MdixEnumCodeGenerator
    {
        /// <summary>
        /// Reads a <c>.mdix</c> file from disk and generates C# enum declarations from
        /// its <c>@ENUMS</c> section. See <see cref="GenerateFromSource"/> for details.
        /// </summary>
        public static MdixResult<string> GenerateFromFile(
            string path,
            string @namespace = "MidManStudio.Mdix.Generated",
            string accessModifier = "public")
        {
            if (path is null)
                return MdixError.NativeError("GenerateFromFile: path cannot be null.");

            string source;
            try
            {
                source = File.ReadAllText(path);
            }
            catch (Exception ex)
            {
                return MdixError.IoError($"GenerateFromFile: could not read '{path}': {ex.Message}", ex);
            }

            return GenerateFromSource(source, @namespace, accessModifier);
        }

        /// <summary>
        /// Parses the <c>@ENUMS</c> section out of raw <c>.mdix</c> source text and
        /// renders it as a C# source file containing one <c>enum</c> declaration per
        /// DixScript enum, wrapped in <paramref name="namespace"/>.
        /// </summary>
        /// <param name="mdixSource">Raw <c>.mdix</c> source text.</param>
        /// <param name="namespace">Namespace the generated enums are declared in.</param>
        /// <param name="accessModifier">Either <c>"public"</c> or <c>"internal"</c>.</param>
        /// <returns>
        /// The generated C# source on success. Fails if <paramref name="mdixSource"/> has
        /// no <c>@ENUMS</c> section, if the section is malformed, or if
        /// <paramref name="accessModifier"/> is not <c>"public"</c>/<c>"internal"</c>.
        /// </returns>
        public static MdixResult<string> GenerateFromSource(
            string mdixSource,
            string @namespace = "MidManStudio.Mdix.Generated",
            string accessModifier = "public")
        {
            if (mdixSource is null)
                return MdixError.NativeError("GenerateFromSource: mdixSource cannot be null.");
            if (string.IsNullOrWhiteSpace(@namespace))
                return MdixError.NativeError("GenerateFromSource: namespace cannot be null or empty.");
            if (accessModifier != "public" && accessModifier != "internal")
                return MdixError.NativeError(
                    "GenerateFromSource: accessModifier must be \"public\" or \"internal\", " +
                    $"got \"{accessModifier}\".");

            // Comments can legally contain '{', '}', '=', ',' -- strip them first via the
            // real DixScript tokenizer (native, correct) so the lightweight scanner below
            // never has to reason about comment syntax itself.
            var stripped = MdixConverter.StripComments(mdixSource);
            if (stripped.IsFailure)
                return MdixError.NativeError($"GenerateFromSource: {stripped.Error.Message}");

            var parsed = ParseEnumsSection(stripped.SuccessResult);
            if (parsed.IsFailure)
                return parsed.Error;

            var enums = parsed.SuccessResult;
            if (enums.Count == 0)
                return MdixError.ParseError(
                    "GenerateFromSource: no @ENUMS section found (or it was empty) -- nothing to generate.");

            return MdixResult<string>.Ok(Render(enums, @namespace, accessModifier));
        }

        // ── Rendering ────────────────────────────────────────────────────────────

        private static string Render(List<ParsedEnum> enums, string @namespace, string accessModifier)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by MdixEnumCodeGenerator from a .mdix @ENUMS section.");
            sb.AppendLine("//     Do not edit by hand -- regenerate instead when the source .mdix changes.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.Append("namespace ").Append(@namespace).AppendLine();
            sb.AppendLine("{");

            for (var i = 0; i < enums.Count; i++)
            {
                var e = enums[i];
                sb.Append("    ").Append(accessModifier).Append(" enum ")
                  .Append(EscapeIdentifier(e.Name)).AppendLine();
                sb.AppendLine("    {");

                for (var j = 0; j < e.Fields.Count; j++)
                {
                    var f = e.Fields[j];
                    sb.Append("        ").Append(EscapeIdentifier(f.Name));
                    if (f.Value.HasValue)
                        sb.Append(" = ").Append(f.Value.Value.ToString(CultureInfo.InvariantCulture));
                    if (j < e.Fields.Count - 1) sb.Append(',');
                    sb.AppendLine();
                }

                sb.AppendLine("    }");
                if (i < enums.Count - 1) sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
            "checked", "class", "const", "continue", "decimal", "default", "delegate",
            "do", "double", "else", "enum", "event", "explicit", "extern", "false",
            "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
            "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
            "new", "null", "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
            "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
        };

        // DixScript identifiers follow the same rule as C# identifiers (letter/underscore
        // start, then alphanumeric/underscore), so the only thing that can make a
        // syntactically valid DixScript name fail to compile as a C# name is colliding
        // with a reserved keyword -- escape those with '@' rather than rejecting them.
        private static string EscapeIdentifier(string name) =>
            CSharpKeywords.Contains(name) ? "@" + name : name;

        // ── Parsing ──────────────────────────────────────────────────────────────

        private sealed class ParsedEnumField
        {
            public string Name = string.Empty;
            public int? Value;
        }

        private sealed class ParsedEnum
        {
            public string Name = string.Empty;
            public List<ParsedEnumField> Fields = new List<ParsedEnumField>();
        }

        private static MdixResult<List<ParsedEnum>> ParseEnumsSection(string source)
        {
            var startIdx = FindSectionStart(source);
            if (startIdx < 0)
                // No @ENUMS section is not an error in isolation -- every section in a
                // .mdix file is optional. GenerateFromSource turns an empty result into
                // a clearer top-level error, since generating nothing is never useful.
                return MdixResult<List<ParsedEnum>>.Ok(new List<ParsedEnum>());

            var openParen = source.IndexOf('(', startIdx);
            if (openParen < 0)
                return MdixError.ParseError("Found '@ENUMS' but no opening '(' followed it.");

            var closeParen = FindMatchingParen(source, openParen);
            if (closeParen < 0)
                return MdixError.ParseError("'@ENUMS(' is missing its matching ')'.");

            var body = source.Substring(openParen + 1, closeParen - openParen - 1);
            return ParseEnumDeclarations(body);
        }

        private static int FindSectionStart(string source)
        {
            // Match "@ENUMS" as a whole token -- not followed by another identifier
            // character, so e.g. a hypothetical future "@ENUMSX" section can never
            // be mistaken for this one.
            var idx = 0;
            while (true)
            {
                idx = source.IndexOf("@ENUMS", idx, StringComparison.Ordinal);
                if (idx < 0) return -1;

                var afterEnd = idx + "@ENUMS".Length;
                var followedByIdentChar = afterEnd < source.Length && IsIdentChar(source[afterEnd]);
                if (!followedByIdentChar) return idx;

                idx = afterEnd;
            }
        }

        private static int FindMatchingParen(string source, int openIdx)
        {
            var depth = 0;
            for (var i = openIdx; i < source.Length; i++)
            {
                if (source[i] == '(') depth++;
                else if (source[i] == ')')
                {
                    depth--;
                    if (depth == 0) return i;
                }
            }
            return -1;
        }

        private static MdixResult<List<ParsedEnum>> ParseEnumDeclarations(string body)
        {
            var result = new List<ParsedEnum>();
            var i = 0;

            while (true)
            {
                SkipWhitespaceAndSeparators(body, ref i);
                if (i >= body.Length) break;

                var nameStart = i;
                if (!IsIdentStartChar(body[i]))
                    return MdixError.ParseError(
                        $"Expected an enum name at position {i} in @ENUMS, found '{body[i]}'.");
                i++;
                while (i < body.Length && IsIdentChar(body[i])) i++;
                var enumName = body.Substring(nameStart, i - nameStart);

                SkipWhitespaceAndSeparators(body, ref i);
                if (i >= body.Length || body[i] != '{')
                    return MdixError.ParseError(
                        $"Expected '{{' after enum name '{enumName}' in @ENUMS.");
                i++; // consume '{'

                var fieldsResult = ParseFields(body, ref i, enumName);
                if (fieldsResult.IsFailure)
                    return fieldsResult.Error;

                result.Add(new ParsedEnum { Name = enumName, Fields = fieldsResult.SuccessResult });
            }

            return MdixResult<List<ParsedEnum>>.Ok(result);
        }

        private static MdixResult<List<ParsedEnumField>> ParseFields(string body, ref int i, string enumName)
        {
            var fields = new List<ParsedEnumField>();

            while (true)
            {
                SkipWhitespaceAndSeparators(body, ref i);
                if (i >= body.Length)
                    return MdixError.ParseError($"Enum '{enumName}' is missing its closing '}}'.");

                if (body[i] == '}')
                {
                    i++;
                    return MdixResult<List<ParsedEnumField>>.Ok(fields);
                }

                var fieldStart = i;
                if (!IsIdentStartChar(body[i]))
                    return MdixError.ParseError(
                        $"Expected a field name in enum '{enumName}' at position {i}, found '{body[i]}'.");
                i++;
                while (i < body.Length && IsIdentChar(body[i])) i++;
                var fieldName = body.Substring(fieldStart, i - fieldStart);

                int? value = null;

                var beforeEquals = i;
                SkipWhitespace(body, ref i);
                if (i < body.Length && body[i] == '=')
                {
                    i++;
                    SkipWhitespace(body, ref i);

                    var signAndDigitsStart = i;
                    if (i < body.Length && (body[i] == '-' || body[i] == '+')) i++;
                    var digitsStart = i;
                    while (i < body.Length && char.IsDigit(body[i])) i++;

                    if (i == digitsStart)
                        return MdixError.ParseError(
                            $"Expected an integer value for field '{fieldName}' in enum '{enumName}'.");

                    var numText = body.Substring(signAndDigitsStart, i - signAndDigitsStart);
                    if (!int.TryParse(numText, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out var parsedValue))
                        return MdixError.ParseError(
                            $"Field '{fieldName}' in enum '{enumName}' has a value ('{numText}') " +
                            "that doesn't fit in a 32-bit integer.");

                    value = parsedValue;
                }
                else
                {
                    // Not a '=' -- this field has no explicit value. Rewind past the
                    // whitespace we just skipped so the outer loop's own
                    // SkipWhitespaceAndSeparators sees it fresh; harmless either way,
                    // but keeps position bookkeeping predictable for future edits here.
                    i = beforeEquals;
                }

                fields.Add(new ParsedEnumField { Name = fieldName, Value = value });
            }
        }

        private static bool IsIdentStartChar(char c) => char.IsLetter(c) || c == '_';
        private static bool IsIdentChar(char c)      => char.IsLetterOrDigit(c) || c == '_';

        private static void SkipWhitespace(string s, ref int i)
        {
            while (i < s.Length && char.IsWhiteSpace(s[i])) i++;
        }

        private static void SkipWhitespaceAndSeparators(string s, ref int i)
        {
            while (i < s.Length && (char.IsWhiteSpace(s[i]) || s[i] == ',')) i++;
        }
    }
}
