#ifndef MDIX_FFI_H
#define MDIX_FFI_H

#pragma once

/* Warning: this file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Controls how DixScript source or database content is formatted.
// Passed to mdix_to_mdix() and mdix_format_source().
enum MdixFormatMode {
    // Readable output with standard 2-space indentation.
    MDIX_FORMAT_MODE_DEFAULT = 0,
    // Readable output with 4-space indentation and sorted keys.
    MDIX_FORMAT_MODE_PRETTY = 1,
    // Compact output — trailing whitespace removed, blank lines collapsed.
    MDIX_FORMAT_MODE_COMPACT = 2,
    // Smallest possible output — all unnecessary whitespace removed.
    MDIX_FORMAT_MODE_MINIFIED = 3,
};
typedef int32_t MdixFormatMode;

// Type discriminants returned by mdix_get_type().
//
// Maps 1:1 to DixValue variants. Use these constants on the C# side to decide
// which getter to call after mdix_get_type() returns.
// Unknown (-1) means the path does not exist or the handle is null.
enum MdixType {
    MDIX_TYPE_UNKNOWN = -1,
    MDIX_TYPE_NULL = 0,
    MDIX_TYPE_BOOL = 1,
    MDIX_TYPE_INT = 2,
    MDIX_TYPE_FLOAT = 3,
    MDIX_TYPE_DOUBLE = 4,
    MDIX_TYPE_STRING = 5,
    MDIX_TYPE_DATE = 6,
    MDIX_TYPE_TIMESTAMP = 7,
    MDIX_TYPE_HEX_COLOR = 8,
    MDIX_TYPE_BLOB = 9,
    MDIX_TYPE_REGEX = 10,
    MDIX_TYPE_ARRAY = 11,
    MDIX_TYPE_OBJECT = 12,
    MDIX_TYPE_TUPLE = 13,
    MDIX_TYPE_ENUM = 14,
};
typedef int32_t MdixType;

// Return the DixScript library version as a null-terminated C string.
//
// The returned pointer is static — do NOT free it with mdix_free_string.
 const char *mdix_version(void) ;

// Load a plain .mdix file from disk.
//
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
// On failure, call mdix_get_last_error() for a description.
 void *mdix_load(const char *path) ;

// Load a .mdix file from a raw source string (no disk access).
//
// Useful for loading .mdix content bundled as a TextAsset in Unity.
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
 void *mdix_load_str(const char *source) ;

// Load an encrypted .mdix.enc file using a key file for decryption.
//
// `enc_path` — path to the .mdix.enc file.
// `key_path` — path to the .mdix.key file, or null to auto-detect next to the .enc file.
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
 void *mdix_load_encrypted(const char *enc_path, const char *key_path) ;

// Load an encrypted .mdix.enc file using a password for decryption.
//
// `enc_path` — path to the .mdix.enc file.
// `password` — decryption password (must match the one used during compilation).
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
 void *mdix_load_encrypted_password(const char *enc_path, const char *password) ;

// Load encrypted data from raw bytes with the key file contents as a string.
//
// `encrypted_bytes`  — pointer to the encrypted data buffer.
// `byte_count`       — number of bytes in the buffer.
// `key_file_content` — full text content of the .mdix.key file.
// `password`         — decryption password, or null if key file mode.
// Returns an opaque void pointer on success, null on failure.

void *mdix_load_encrypted_bytes(const uint8_t *encrypted_bytes,
                                int32_t byte_count,
                                const char *key_file_content,
                                const char *password)
;

// Free a handle returned by any mdix_load* function.
//
// After calling this the pointer is invalid — do not use it again.
// Passing null is safe and does nothing.
 void mdix_free(void *handle) ;

// Return true if the handle pointer is non-null.
 bool mdix_is_valid(const void *handle) ;

// Return the total number of data entries in the loaded file.
//
// Returns -1 if the handle is null.
 int32_t mdix_entry_count(const void *handle) ;

// Return the MdixType discriminant of the value at the given path.
//
// Returns MdixType::Unknown (-1) if the path does not exist or the handle is null.
 MdixType mdix_get_type(const void *handle, const char *path) ;

// Return the number of items in the array at the given path.
//
// Returns -1 if the path does not exist, the value is not an array, or handle is null.
 int32_t mdix_get_array_length(const void *handle, const char *path) ;

// Get a string value by dotted path.
//
// Also works for Date, Timestamp, and HexColor — all are stored as strings.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_get_string(const void *handle, const char *path) ;

// Get an integer value by dotted path.
//
// Also works for Enum values — returns the resolved integer (e.g. BOSS → 2).
// Returns 0 on failure. Use mdix_exists() to distinguish 0 from not-found.
 int32_t mdix_get_int(const void *handle, const char *path) ;

// Get a float (f32) value by dotted path. Returns 0.0 on failure.
 float mdix_get_float(const void *handle, const char *path) ;

// Get a double (f64) value by dotted path. Returns 0.0 on failure.
 double mdix_get_double(const void *handle, const char *path) ;

// Get a boolean value by dotted path. Returns false on failure.
 bool mdix_get_bool(const void *handle, const char *path) ;

// Return the enum type name at the given path (e.g. "AIType").
//
// Returns null if the path does not exist or is not an enum.
// The caller must free the result with mdix_free_string().
 char *mdix_get_enum_name(const void *handle, const char *path) ;

// Return the enum field name at the given path (e.g. "BOSS").
//
// Returns null if the path does not exist or is not an enum.
// The caller must free the result with mdix_free_string().
 char *mdix_get_enum_field(const void *handle, const char *path) ;

// Serialize the value at the given path to a JSON string.
//
// Escape hatch for Blob, Regex, Tuple, and any nested structure.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_get_json(const void *handle, const char *path) ;

// Check whether a dotted path exists in the loaded data.
//
// Returns false if the handle is null.
 bool mdix_exists(const void *handle, const char *path) ;

// Get the direct child key names under a path prefix.
//
// `prefix`    — dotted path prefix, or null / empty string for top-level keys.
// `out_count` — receives the number of keys returned. Must not be null.
//
// Returns a heap-allocated array of null-terminated C strings, or null if empty.
// The caller must free the result with mdix_free_string_array(result, out_count).
 char **mdix_get_keys(const void *handle, const char *prefix, int32_t *out_count) ;

// Free a string returned by any mdix getter that returns *mut c_char.
//
// Passing null is safe. Do NOT call this on the pointer from mdix_version().
 void mdix_free_string(char *s) ;

// Free an array of strings returned by mdix_get_keys.
//
// `arr`   — pointer returned by mdix_get_keys.
// `count` — value written to out_count by mdix_get_keys.
 void mdix_free_string_array(char **arr, int32_t count) ;

// Return the last error message as a null-terminated C string, or null on success.
//
// The returned pointer is valid only until the next mdix FFI call.
// Copy the string immediately — do not cache the pointer.
// Do NOT free this pointer.
 const char *mdix_get_last_error(void) ;

// Clear the last error without making any other call.
 void mdix_clear_error(void) ;

// Export all entries in the loaded database as a JSON string.
//
// Dotted-path nesting is reconstructed automatically.
// `indented` — pass true for pretty-printed JSON, false for compact single-line.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_to_json(const void *handle, bool indented) ;

// Serialize the loaded database back to .mdix text format.
//
// `mode` — one of the MdixFormatMode values controlling output style.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 void *mdix_to_mdix(const void *handle, MdixFormatMode mode) ;

// Format a raw .mdix source string according to the requested mode.
//
// `source` — null-terminated UTF-8 .mdix source.
// `mode`   — one of the MdixFormatMode values.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_format_source(const char *source, MdixFormatMode mode) ;

// Minify a raw .mdix source string — remove all unnecessary whitespace and comments.
//
// String literal contents are preserved.
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_minify_source(const char *source) ;

// Create a new empty builder handle.
//
// Returns an opaque void pointer. The caller must free it with mdix_builder_free().
 void *mdix_builder_new(void) ;

// Free a builder handle. Passing null is safe.
 void mdix_builder_free(void *builder) ;

// Return the number of entries currently in the builder. Returns -1 if null.
 int32_t mdix_builder_entry_count(const void *builder) ;

// Remove all entries from the builder without freeing the handle.
//
// Returns true on success, false if the builder is null.
 bool mdix_builder_clear(void *builder) ;

// Set a string value at the given dotted path. Returns true on success.
 bool mdix_builder_set_string(void *builder, const char *path, const char *value) ;

// Set an integer value at the given dotted path. Returns true on success.
 bool mdix_builder_set_int(void *builder, const char *path, int32_t value) ;

// Set a float value at the given dotted path. Returns true on success.
 bool mdix_builder_set_float(void *builder, const char *path, float value) ;

// Set a double value at the given dotted path. Returns true on success.
 bool mdix_builder_set_double(void *builder, const char *path, double value) ;

// Set a boolean value at the given dotted path. Returns true on success.
 bool mdix_builder_set_bool(void *builder, const char *path, bool value) ;

// Remove a key from the builder. Returns true if it existed and was removed.
 bool mdix_builder_remove(void *builder, const char *path) ;

// Check whether a key exists in the builder.
 bool mdix_builder_has_key(const void *builder, const char *path) ;

// Get a string value from the builder by dotted path.
//
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_builder_get_string(const void *builder, const char *path) ;

// Get an integer value from the builder by dotted path. Returns 0 on failure.
 int32_t mdix_builder_get_int(const void *builder, const char *path) ;

// Get a float value from the builder by dotted path. Returns 0.0 on failure.
 float mdix_builder_get_float(const void *builder, const char *path) ;

// Get a double value from the builder by dotted path. Returns 0.0 on failure.
 double mdix_builder_get_double(const void *builder, const char *path) ;

// Get a boolean value from the builder by dotted path. Returns false on failure.
 bool mdix_builder_get_bool(const void *builder, const char *path) ;

// Save the builder contents to a .mdix file on disk.
//
// Creates the file and any intermediate directories automatically.
// Returns true on success, false on failure.
 bool mdix_builder_save(const void *builder, const char *path) ;

// Serialize the builder contents to a .mdix format string.
//
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_builder_to_string(const void *builder) ;

// Export all entries in the loaded database as a TOML string.
//
// Returns a heap-allocated C string on success, null on failure.
// The caller must free the result with mdix_free_string().
 char *mdix_to_toml(const void *handle) ;

// Load a JSON string and return a handle to the parsed data.
//
// The JSON must be an object at the top level.
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
 void *mdix_from_json(const char *source) ;

// Load a TOML string and return a handle to the parsed data.
//
// The TOML must be a table at the top level.
// Returns an opaque void pointer on success, null on failure.
// The caller must free the handle with mdix_free() when done.
 void *mdix_from_toml(const char *source) ;

#endif /* MDIX_FFI_H */
