// com.midmanstudio.mdix.webgl/Runtime/Plugins/WebGL/MdixWeb.jslib
//
// ── WHY THIS FILE EXISTS ─────────────────────────────────────────────────────
// mdix-ffi (the native P/Invoke backend used by MdixDatabase.cs on every other
// platform) cannot be built for Unity WebGL: Unity WebGL statically links the
// whole player into one Emscripten module at build time, and there is no
// wasm32-unknown-emscripten build of mdix-ffi (see mdix-ffi/Cargo.toml's own
// "WebGL: NOT SUPPORTED" comment). mdix-wasm (wasm32-unknown-unknown, built
// via wasm-pack) *can* run in the browser, so this file bridges to it.
//
// ── WHY THE FUNCTION NAMES BELOW MATCH mdix_ffi/src/lib.rs EXACTLY ──────────
// MdixNative.cs (generated by csbindgen from mdix-ffi/src/lib.rs) declares
// `[DllImport("mdix_ffi")] static extern ... mdix_load_str(...)` etc. and
// MdixDatabase.cs / MdixSafeHandle.cs call those methods directly — nothing
// in mdix-csharp is Unity-aware (it also ships as a plain netstandard2.1
// NuGet package, so it deliberately has no UNITY_WEBGL branches, and in fact
// *can't* have any: MidManStudio.Mdix.Core.dll is compiled exactly once by a
// plain `dotnet build` in CI (see .github/workflows/build-upm.yml's
// build-core-dll job), which never defines UNITY_WEBGL/UNITY_IOS/UNITY_EDITOR
// — those are Unity-compiler-only symbols. Any #if UNITY_WEBGL written inside
// mdix-csharp would silently always take the #else branch in the shipped DLL.
//
// On WebGL, IL2CPP resolves P/Invoke externs by FUNCTION NAME against
// whatever .jslib symbols are merged in at build time — the DllImport
// library-name string ("mdix_ffi") is not used for symbol resolution on this
// platform (unlike Windows/Linux/macOS/Android, where it names a real
// dynamic library to open). So: as long as this file exports a JS function
// named exactly `mdix_load_str`, IL2CPP wires the *existing*, *unmodified*
// `MdixNative.mdix_load_str(...)` call straight into it. Zero changes needed
// anywhere in mdix-csharp or the generated bindings.
//
// ── SCOPE OF THIS FIRST SLICE ────────────────────────────────────────────────
// Implemented:  mdix_load_str, mdix_free, mdix_get_string, mdix_get_int,
//               mdix_get_bool, mdix_exists, mdix_entry_count,
//               mdix_free_string, mdix_get_last_error, mdix_clear_error.
// NOT implemented: mdix_load (file path — no filesystem story on WebGL yet),
//               mdix_load_encrypted*, mdix_get_long/float/double/json,
//               mdix_get_enum_*, mdix_get_keys, mdix_to_*, merge/builder/
//               schema functions, etc. If a WebGL build's IL2CPP link step
//               fails with "undefined symbol: _mdix_xxx", that means some
//               code path (yours or MdixConverter/MdixSchema/etc.) reached
//               one of these unported functions — either avoid that call on
//               WebGL for now, or add a matching shim below using the same
//               pattern (check mdix-ffi/src/lib.rs for the exact signature
//               and error-handling contract of the function you're adding).
//
// ── HANDLE REPRESENTATION ────────────────────────────────────────────────────
// Native mdix_ffi hands back a real heap pointer as the opaque `void*`
// handle. We have no such pointer — mdix-wasm's MdixDatabase is a JS/wasm
// object, not a C-ABI pointer. So we keep a small integer -> object registry
// here and hand C# the integer *as if* it were the pointer. C# never
// dereferences it (SafeHandle/MdixDatabase treat it as fully opaque), it
// only ever round-trips it back into mdix_free / mdix_get_string / etc., so
// this is safe. 0 is reserved for "null" (mirrors native's null-on-failure
// convention — see mdix_load_str's doc comment in mdix-ffi/src/lib.rs).
//
// ── REQUIRED SETUP (does not work out of the box) ────────────────────────────
// This file only wires the C ABI shim. Something must still load the actual
// mdix-wasm module and publish it as `window.__mdixWasm` with
// `window.__mdixReady = true` once ready, BEFORE any mdix_load_str call.
// See mdix-bootstrap.js (add its <script type="module"> tag to your WebGL
// template's <head>) and MdixWebGLReady.cs (poll/await readiness from C#
// before calling Dix.LoadStr on WebGL). Calling mdix_load_str before the
// bootstrap finishes returns 0 / a "not ready" error — it will not hang or
// crash, but it also will not silently wait for you.

mergeInto(LibraryManager.library, {

  // ── Shared state ────────────────────────────────────────────────────────
  $mdixState: {
    registry: {},      // int id -> mdix-wasm MdixDatabase instance
    nextId: 1,          // 0 is reserved for "null handle"
    lastError: null,    // string | null
    errBufPtr: 0,        // scratch heap buffer reused by mdix_get_last_error
    errBufLen: 0,
  },

  // ── Internal helpers (not part of the mdix_ffi ABI — $-prefixed so they
  //    are never exposed as callable P/Invoke symbols themselves) ─────────
  $mdixSetError__deps: ['$mdixState'],
  $mdixSetError: function (context, err) {
    var msg = (err && err.message) ? err.message
            : (typeof err === 'string') ? err
            : (err ? String(err) : 'unknown error');
    mdixState.lastError = context + ': ' + msg;
  },

  $mdixAllocUtf8__deps: [],
  $mdixAllocUtf8: function (str) {
    var len = lengthBytesUTF8(str) + 1;
    var ptr = _malloc(len);
    stringToUTF8(str, ptr, len);
    return ptr;
  },

  // ── Readiness (bridge-only helper — NOT a real mdix_ffi export, hence the
  //    mdix_web_ prefix instead of mdix_, so it can never collide with a
  //    real future mdix_ffi symbol) ──────────────────────────────────────
  mdix_web_is_ready: function () {
    return (typeof window !== 'undefined' && window.__mdixReady) ? 1 : 0;
  },

  // ── mdix_load_str(source: *const c_char) -> *mut c_void ─────────────────
  // Rust: clears the error, returns null (0) handle on failure.
  mdix_load_str__deps: ['$mdixState', '$mdixSetError'],
  mdix_load_str: function (sourcePtr) {
    mdixState.lastError = null;
    try {
      if (!(typeof window !== 'undefined' && window.__mdixReady && window.__mdixWasm)) {
        mdixState.lastError =
          'mdix_load_str: mdix-wasm module is not ready yet. ' +
          'Wait for MdixWebGLReady.WaitUntilReady() (or window.__mdixReady) ' +
          'before calling Dix.LoadStr on WebGL.';
        return 0;
      }
      var source = UTF8ToString(sourcePtr);
      var db = window.__mdixWasm.MdixDatabase.loadStr(source);
      var id = mdixState.nextId++;
      mdixState.registry[id] = db;
      return id;
    } catch (e) {
      mdixSetError('mdix_load_str', e);
      return 0;
    }
  },

  // ── mdix_free(handle: *mut c_void) -> void ───────────────────────────────
  // Rust: "passing null is safe, do not call twice." We mirror both: no-op
  // on 0, and delete-from-registry makes a second call locally safe too
  // (the underlying mdix-wasm object won't be double-freed).
  mdix_free__deps: ['$mdixState'],
  mdix_free: function (handle) {
    if (!handle) return;
    var db = mdixState.registry[handle];
    if (!db) return;
    delete mdixState.registry[handle];
    try { db.free(); } catch (e) { /* already freed / nothing to release */ }
  },

  // ── mdix_get_string(handle, path: *const c_char) -> *mut c_char ─────────
  // Rust: clears the error internally, returns null on failure. Every
  // success allocates a *fresh* buffer the caller must free via
  // mdix_free_string (matches ReadFreeNativeString's contract in
  // MdixDatabase.cs — do not reuse errBufPtr's buffer for this).
  mdix_get_string__deps: ['$mdixState', '$mdixSetError', '$mdixAllocUtf8'],
  mdix_get_string: function (handle, pathPtr) {
    mdixState.lastError = null;
    var db = mdixState.registry[handle];
    if (!db) { mdixState.lastError = 'mdix_get_string: invalid or freed handle'; return 0; }
    try {
      var path = UTF8ToString(pathPtr);
      var value = db.getString(path);
      return mdixAllocUtf8(value);
    } catch (e) {
      mdixSetError("mdix_get_string('" + UTF8ToString(pathPtr) + "')", e);
      return 0;
    }
  },

  // ── mdix_get_int(handle, path) -> i32 ────────────────────────────────────
  // Rust: clears the error, returns 0 on failure (caller must check
  // mdix_get_last_error to distinguish from a real 0 — GetInt() in
  // MdixDatabase.cs already does this for every platform).
  mdix_get_int__deps: ['$mdixState', '$mdixSetError'],
  mdix_get_int: function (handle, pathPtr) {
    mdixState.lastError = null;
    var db = mdixState.registry[handle];
    if (!db) { mdixState.lastError = 'mdix_get_int: invalid or freed handle'; return 0; }
    try {
      var path = UTF8ToString(pathPtr);
      return db.getInt(path) | 0;
    } catch (e) {
      mdixSetError("mdix_get_int('" + UTF8ToString(pathPtr) + "')", e);
      return 0;
    }
  },

  // ── mdix_get_bool(handle, path) -> bool ──────────────────────────────────
  // Rust: clears the error, returns false on failure. Returned as a plain
  // 0/1 number — IL2CPP's WebGL P/Invoke bridge reads bool returns as a
  // number regardless of the C# MarshalAs attribute used on this platform,
  // this is the standard Unity WebGL jslib bool-return idiom.
  mdix_get_bool__deps: ['$mdixState', '$mdixSetError'],
  mdix_get_bool: function (handle, pathPtr) {
    mdixState.lastError = null;
    var db = mdixState.registry[handle];
    if (!db) { mdixState.lastError = 'mdix_get_bool: invalid or freed handle'; return 0; }
    try {
      var path = UTF8ToString(pathPtr);
      return db.getBool(path) ? 1 : 0;
    } catch (e) {
      mdixSetError("mdix_get_bool('" + UTF8ToString(pathPtr) + "')", e);
      return 0;
    }
  },

  // ── mdix_exists(handle, path) -> bool ────────────────────────────────────
  // Rust: false on null handle / invalid UTF-8 / not found — never sets an
  // error (matches Exists() in MdixDatabase.cs, which ignores TryGetRawHandle's
  // error output entirely).
  mdix_exists__deps: ['$mdixState'],
  mdix_exists: function (handle, pathPtr) {
    var db = mdixState.registry[handle];
    if (!db) return 0;
    try {
      var path = UTF8ToString(pathPtr);
      return db.exists(path) ? 1 : 0;
    } catch (e) {
      return 0;
    }
  },

  // ── mdix_entry_count(handle) -> i32 ──────────────────────────────────────
  // Rust: -1 if handle is null/invalid.
  mdix_entry_count__deps: ['$mdixState'],
  mdix_entry_count: function (handle) {
    var db = mdixState.registry[handle];
    if (!db) return -1;
    try {
      return db.entryCount | 0;
    } catch (e) {
      return -1;
    }
  },

  // ── mdix_free_string(s: *mut c_char) -> void ─────────────────────────────
  // Frees a per-call buffer allocated by mdix_get_string (mdixAllocUtf8).
  // Never call this on the pointer returned by mdix_get_last_error — that
  // one is a reused scratch buffer, not a per-call allocation (matches the
  // native contract: "do NOT free this pointer").
  mdix_free_string: function (ptr) {
    if (ptr) _free(ptr);
  },

  // ── mdix_get_last_error() -> *const c_char ───────────────────────────────
  // Rust: "valid only until the next mdix_* call on this thread, do not
  // free." We reuse one scratch buffer and grow it on demand instead of
  // allocating fresh memory per call, to match that no-free contract.
  mdix_get_last_error__deps: ['$mdixState'],
  mdix_get_last_error: function () {
    if (!mdixState.lastError) return 0;
    var len = lengthBytesUTF8(mdixState.lastError) + 1;
    if (mdixState.errBufLen < len) {
      if (mdixState.errBufPtr) _free(mdixState.errBufPtr);
      mdixState.errBufPtr = _malloc(len);
      mdixState.errBufLen = len;
    }
    stringToUTF8(mdixState.lastError, mdixState.errBufPtr, mdixState.errBufLen);
    return mdixState.errBufPtr;
  },

  // ── mdix_clear_error() -> void ───────────────────────────────────────────
  mdix_clear_error__deps: ['$mdixState'],
  mdix_clear_error: function () {
    mdixState.lastError = null;
  },

});
